pom.xml
src/main/java/fr/insee/eno/Constants.java
src/main/java/fr/insee/eno/DummyMain.java
src/main/java/fr/insee/eno/xsl/FodsToXSLCompiler.java

Code Review: 4de69f4
- Maven goal now adds generated assets to classpath
- *Note: developers must run ```mvn package``` before running the project*
- DummyMain filepath is now given as a program argument
- Typo was fixed in Constants.java

Add generated assets to classpath

---

src/main/java/fr/insee/eno/Constants.java
src/main/java/fr/insee/eno/GenerationService.java
src/main/java/fr/insee/eno/generation/DDI2FRGenerator.java
src/main/java/fr/insee/eno/generation/DDI2ODTGenerator.java
src/main/java/fr/insee/eno/generation/DDI2PDFGenerator.java
src/main/java/fr/insee/eno/generation/PoguesXML2DDIGenerator.java
src/main/java/fr/insee/eno/postprocessing/CustomizationPostprocessor.java
src/main/java/fr/insee/eno/postprocessing/PDFPostprocessor.java
src/main/java/fr/insee/eno/transform/xsl/XslParameters.java
src/main/java/fr/insee/eno/transform/xsl/XslTransformation.java
src/main/resources/xslt/outputs/pdf/home-page.xsl
src/main/resources/xslt/outputs/pdf/models.xsl
src/main/resources/xslt/outputs/pdf/publipostage.xsl
src/main/scripts/build-ddi2pdf.xml
src/main/scripts/build-pdf.xml
src/test/java/fr/insee/eno/main/DummyTestDDI2FO.java
src/test/java/fr/insee/eno/main/DummyTestDDI2FOWithPlugins.java
src/test/java/fr/insee/eno/main/DummyTestDDI2ODT.java
src/test/java/fr/insee/eno/main/DummyTestDDI2PDF.java
src/test/java/fr/insee/eno/main/DummyTestDDI2PDFExamples.java
src/test/java/fr/insee/eno/main/DummyTestDDI2XForms.java
src/test/java/fr/insee/eno/main/DummyTestPoguesXML2DDI.java
src/test/java/fr/insee/eno/test/TestDDIToFO.java
src/test/java/fr/insee/eno/test/TestDDIToODT.java
src/test/java/fr/insee/eno/test/TestDDIToXForm.java
src/test/java/fr/insee/eno/test/TestPoguesXMLToDDI.java

prise en compte des points remontés par Benoit et François (CF mails du 16 et 17 juillet) + améliorations/nettoyage code.
1/ Il faut paramétrer et rendre plus générique la transformation 
2/ récupération des attributs du noeud contenant le pattern à matcher (prise en compte remarque de François)
3/ traiter la séparation entre les noeuds de réponses et les autres noeuds=>
If variable then variable else "..." 
ne doit s'appliquer que pour les formats de réponse de type texte pas
partout...
Exemple ici avec la question 5, on retrouve les .......... alors que
c'est une instruction, le format de réponse arrive ensuite (format
date).
4/création d'un post processor de publipostage séparé
5/ inclusion de l'appel du postprocessor de publipostage dans la chaine ant
6- Prise en compte de la …

Publipostage Suite 

---

src/main/resources/xslt/outputs/fr/models.xsl
src/main/resources/xslt/transformations/ddi2fr/ddi2fr-fixed.xsl
src/main/resources/xslt/transformations/ddi2fr/functions.fods
src/main/resources/xslt/util/ddi/ddi32toddi33.xsl
src/main/resources/xslt/util/ddi/dereferencing.xsl
src/test/resources/ddi-to-xform/out.xhtml

- standard date : xf:input, not fr:number
- current-date() is not allowed in XForms
- use of the attribute suffix of fr:number
- is-required must always be false and checks must always be warning for Web questionnaires
- add a special numeric formula : string(var) = ''
- dereferencing made space characters disappear
- ddi32toddi33 did not list the correct external variables in ant mode for surveys with several questionnaires

bugs with dates and numeric suffix

---

src/main/resources/xslt/util/pogues-xml/goto-2-if-then-else.xsl

We did not expect 98 to be greater than 155... (whereas 9x is after 1xx in alphabetic)

sort @position by numeric order instead of alphabetic order

---

src/main/resources/xslt/outputs/xforms/models.xsl

Regression due to : https://github.com/InseeFr/Eno/pull/280
external variables were forgotten for loops in :
- instance
- model for new occurrences (lost for dynamic arrays too)

bug : external variables lost from loops

---

src/main/resources/xslt/inputs/pogues-xml/source-fixed.xsl

319-BO-Ajout d'une unité pour les réponses simples numériques : semaines
This adds another unit: `semaines` (weeks).

Add unit Weeks

---

questionnaires/esem-2020-a00/fo/m1/form/form.fo
src/main/resources/xslt/post-processing/fo/accompanying-mails/accompagnementCOL.fo
src/main/resources/xslt/post-processing/fo/accompanying-mails/cnrCOL.fo
src/main/resources/xslt/post-processing/fo/accompanying-mails/entreeCOL.fo
src/main/resources/xslt/post-processing/fo/accompanying-mails/medCOL.fo
src/main/resources/xslt/post-processing/fo/accompanying-mails/ouvertureCOL.fo
src/main/resources/xslt/post-processing/fo/accompanying-mails/relanceCOL.fo
src/test/resources/params/in-to-out/business/form.fo

Pour les prochains envois, il faudrait mettre à jour les modèles de courriers simples "fusionnés" avec les questionnaires.
Cela concerne l'adresse postale. La Poste demande pour une meilleure prise en compte des courriers par leurs automates que les adresses soient "plaquées" vers le bas de la zone adresse.
Les modèles de courriers simples utilisés ici n'ont pas cette propriété. Et donc les adresses sont "plaquées" vers le haut (tout près du Barcode).
On risque donc d'avoir un retour de la Poste si on continue à plaquer les adresses vers le haut…

Dev fo update mail

---

src/main/resources/xslt/outputs/fo/models.xsl

Minor modification of xsl template of TextareaDomain to fix behaviour of fo output with the "Other-Give details" option, not showing the arrow and label "Give details" when the field max characters is over 250

Changing template for TextareaDomain in fo output models.xsl to show other/details

---

pom.xml

In the pom.xml the execution of FodsToXSLCompileris set to run at package phase in maven lyfecycle but should run after compilation and before tests so at process-classes phase in order the tests success.

Compile XSL from ods at the right phase of maven lifecycle

---

pom.xml
questionnaires/esem-2020-a00/fo/m1/form/form.fo
src/main/resources/xslt/post-processing/fo/page-first/page-first-business.fo
src/test/resources/params/in-to-out/business/form.fo

Adding meaningful barcode for the cover page of business forms in portrait format. The barcode is of the datamatrix kind and contains {Identifier of surveyed unit} - {Short label of survey} -  {Year of the survey} - {Period of the survey}
It was necessary to modify the fo of business context test (esem) to fit the new format.

Dev fo barcodeinfo

---

pom.xml
src/main/resources/xslt/inputs/pogues-xml/functions.fods
src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/functions.fods

Allowing a ControlConstructReference to point to a QuestionConstruct (for dynamic tables). Until now, it was wrongly pointing as a Loop (in r:TypeOfObject) (by default when pogues xml was transformed in DDI)
To do so : 
- creating a getter enopogues:is-question-construct to check if the Scope in the xml pogues is meant to be a QuestionConstruct 
- testing in ddi output models.xsl and if true, put "QuestionConstruct" in the r:TypeOfObject of d:ControlConstructReference

Hotfix ddi control construct ref for dyntable

---

pom.xml
src/main/resources/xslt/outputs/ddi/models.xsl

Request for Pogues: the referenced variables must be framed by ¤ and not $.
Replacement for any $ character assumed by the Pogues Insee owner.

adding replace $ into ¤ into FlowControl/Description (xmlpogues2ddi)

---

pom.xml
src/main/resources/xslt/pre-processing/pogues-xml/goto-2-if-then-else.xsl

When creating child position list, the case pogues:IfTrue/pogues:Loop was forgotten in the for-each. Just needed to add it so that an IfTrue would correctly point to the Loop

Adding support of filtered loops in pogues-xml

---

pom.xml

Upgrade to (following dependabot suggestions) :
- java 11
- xalan -> 2.7.2
- slf4j -> 1.7.30
- maven source plugin -> 3.2.1
- maven javadoc plugin -> 3.2.0
-  codehaus build helper plugin -> 3.2.0
- Saxon HE -> 9.9.1-8

Upgrade java and dependencies

---

.github/dependabot.yml
pom.xml

Eno-core is a library used by other applications and shouldn't depend over an slf4j implementation (every app has to provide its own slf4j impl). The propose of this PR is to remove the dependency over log4j-slf4j-impl artifact in the library eno-core. The dependency over log4j-slf4j-impl is not transitive any more and is only internally for tests and process classes phase (exec-maven-plugin)

No slf4j impl in Eno library

---

pom.xml

Bumping the Saxon version to 9.9.1-8 : needed since the big dependencies upgrade (w/ Saxon 10.5) is not yet ready to deploy.

Hotfix saxon 9.9.1-8

---

pom.xml
src/main/resources/xslt/pre-processing/ddi/md2xhtml.xsl
src/main/resources/xslt/pre-processing/ddi/tweak-xhtml-for-ddi.xsl

Adding support of links for markdown to xhtml :
- ddi pre-processing md2xhtml : adding support of markdown links (only specific cases were supported so far)
- ddi pre-processing tweak-xhtml-for-ddi : not using xsl:key (does not work) but matches in conditions for footnote pattern recognition

Dev md2xhtml links mailto

---

eno-core/src/main/java/fr/insee/eno/core/DDIToLunatic.java
eno-core/src/main/java/fr/insee/eno/core/output/LunaticSerializer.java
eno-core/src/main/java/fr/insee/eno/core/parameter/EnoParameters.java
eno-core/src/test/java/fr/insee/eno/core/demo/DDIToLunaticTest.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/DDIToLunaticController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/GenerationController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/IntegrationHouseholdController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/SimpleGenerationController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/V3ParameterController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/utils/HeadersUtils.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/utils/V3ControllerUtils.java
eno-ws/src/main/java/fr/insee/eno/ws/service/DDIToLunaticService.java
eno-ws/src/main/java/fr/insee/eno/ws/service/ParameterService.java

#563 
Eno API now uses V3 services for all (four) "DDI to Lunatic" endpoints 🎉 
- Some refactor in `core` to output Lunatic json or xml
- Replace redirection by v3 service call in DDI to Lunatic controllers
The V3 web-service should be ready to be used in combination with Pogues 🥳

feat: V3 services in legacy endpoints

---

eno-core/src/main/java/fr/insee/eno/core/model/calculated/CalculatedExpression.java
eno-core/src/main/java/fr/insee/eno/core/model/label/DynamicLabel.java
eno-core/src/main/java/fr/insee/eno/core/model/label/Label.java
eno-core/src/main/java/fr/insee/eno/core/model/label/QuestionnaireLabel.java
eno-core/src/test/java/fr/insee/eno/core/mappers/lunatic/LabelTests.java

I thought implementation was done for Lunatic labels' "type" property, however there was null values in the result.
To be fixed (+add tests) in this branch.

fix: actually write label types in Lunatic

---

pom.xml
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/pre-processing/ddi/dereferencing.xsl
src/test/resources/pogues-xml-to-ddi/out.xml

The added Sequence has no "d:TypeOfSequence". It makes it invisible to eno-v2, since it is not linked to a Driver.
Tested with ddi2lunatic on ENL : 0 difference on generation.

add a child sequence for loops that don't have a filter on their occurrences

---

eno-core/src/main/java/fr/insee/eno/core/parameter/EnoParameters.java
eno-core/src/test/java/fr/insee/eno/core/DDIToLunaticTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/ddi/DateQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/ddi/DurationQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/CalculatedVariableTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/ComponentFilterTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/NumberQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticLoopResolutionTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticSortComponentsTest.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/DDIToLunaticController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/GenerationController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/SimpleGenerationController.java
eno-ws/src/main/java/fr/insee/eno/ws/service/ParameterService.java

Refactor parameters class to properly separate Eno "core/common" parameters from Lunatic-specific ones.
The class also looks cleaner now.

refactor(parameters): proper separation of Eno and Lunatic parameters

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/model/navigation/StandaloneLoop.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/StandaloneLoopTest.java

Remove duplicates in Lunatic loop dependencies of standalone loops.
NB: dependencies of linked loops are always a single collected variable.
NB2: not yet completely sure that loop dependencies of standalone loops should include either min and max or just max.

fix: remove duplicates in loop dependencies

---

.github/workflows/gandalf.yml
build.gradle
eno-core/src/main/java/fr/insee/eno/core/model/EnoComponent.java
eno-core/src/main/java/fr/insee/eno/core/model/question/Question.java
eno-core/src/main/java/fr/insee/eno/core/model/sequence/AbstractSequence.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIInsertControls.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIResolveVariableReferencesInLabels.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/ddi/DDIInsertControlsTest.java
eno-core/src/test/resources/functional/ddi/ddi-l7j0wwqx.xml
eno-core/src/test/resources/functional/lunatic/lunatic-l7j0wwqx.json
eno-core/src/test/resources/functional/pogues/pogues-l7j0wwqx.json

#732 
Fix issue on the DDI processing that insert controls in questions.

fix: controls in loops and filters

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/parameter/LunaticParameters.java
eno-core/src/test/java/fr/insee/eno/core/parameter/EnoParameterTest.java

Absence of Lunatic pagination makes questionnaires that have loops crash at runtime.

fix: lunatic pagination parameter

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/common/EnoProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/common/steps/EnoAddCommentSection.java
eno-core/src/main/java/fr/insee/eno/core/processing/common/steps/EnoAddPrefixInQuestionLabels.java
eno-core/src/main/java/fr/insee/eno/core/processing/common/steps/EnoAddResponseTimeSection.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/LunaticProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticResponseTimeQuestionPagination.java
eno-core/src/test/java/fr/insee/eno/core/processing/common/steps/EnoAddCommentSectionTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/common/steps/EnoAddResponseTimeSectionTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticResponseTimeQuestionPaginationTest.java

#723 
- Refactor "common" processing classes that insert end "comment" and "response time"
- Add tests on resulting label of these questions
- Add a Lunatic processing for the "response time" hours and minutes components to make these having the same page number
- Add test on the latter

fix: end question labels

---

Dockerfile
build.gradle

Change `eclipse-temurin` base image tag from `17-jre-alpine` to `17-jre-focal` (that include `openssl`)

build(docker): change base image

---

Dockerfile
build.gradle

temurin jre-apline previously used don't run as root, but jre-focal does.
- #781 
➡️ Add non root user in the Dockefile

build(docker): non root user in image

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticFilterResult.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticFinalizePairwise.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticFinalizePairwiseTest.java

- https://github.com/InseeFr/Eno/issues/795
In Lunatc, the unique choice question component within the pairwise component is not deprecated had a condition filter `"xAxis <> yAxis"`. This filter is no more required.

fix: pairwise ucq condition filter

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIInsertResponseInTableCells.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/ddi/DDIInsertResponseInTableCellsTest.java

Responses were not mapped in Lunatic table components generated from  a "complex multiple choice question" (in Pogues, it is a multiple choice question that uses a code list for its responses).
Probably a regression introduced by a side effect of #773
Add complex multiple choice question objects in the `DDIInsertResponsesInTableCells` processing.

fix: insert responses in complex multiple choice questions

---

build.gradle
eno-ws/src/main/java/fr/insee/eno/ws/controller/GenerationStandardController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/exception/EnoExceptionController.java

- #852 
> POST [/questionnaire/{context}/xforms] : Unknown error during generation: SSLTube(SocketTube(5)) stream=1 [reactor-http-epoll-6] Too few bytes returned by the publisher (0/984670)
Cause: an oversight in the code that verifies that the metadata is present in 'business' context.

fix(api): oversight in xforms and fo standard controllers

---

build.gradle
eno-ws/src/main/java/fr/insee/eno/ws/controller/GenerationStandardController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/exception/EnoExceptionController.java
eno-ws/src/main/java/fr/insee/eno/ws/exception/MultiModelException.java

Add a multi-model option in Xforms and FO standard endpoints.
If this option is set to true, the output questionnaire(s) are in a zip file.
Configured it to be required in the "business" context.

feat(api): multi-model option in xforms and fo standard endpoints

---

build.gradle
eno-ws/src/main/java/fr/insee/eno/ws/config/OpenApiConfiguration.java
eno-ws/src/main/resources/application.properties
settings.gradle

Add a "server" instance in the OpenAPI configuration, so that requests sent from the swagger-ui work more reliably.
\+ by the way, changed snapshot to released version of Lunatic-Model.

fix: open api host config

---

.github/workflows/sonar.yml
build.gradle
eno-core/src/main/java/fr/insee/eno/core/model/navigation/Control.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddControlFormat.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddControlFormatTest.java

Having variable criticality introduced a change in Lunatic questionnaire's behavior compared to previous major version of Eno.

fix(controls): info criticality everywhere

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIInsertCodeLists.java

- #862 
- Improve exception management in case a code list referenced in a question (or table cell, or else) is null
Having missing code lists is actually a non-issue in Eno, since this information must be present for the questionnaire to be valid.
To be resolved in Pogues.
Yet, improving the exception handling when this occurs does not hurt 🙃

refactor: null cases handling for ddi code lists

---

.github/workflows/create-release.yml

In order to launch Cast analysis in internal infrastructure by downloading uploaded jar release
I think we can switch default branch to `v3-main` or rename `main` to `v2-legacy` and `v3-main` to `main`

ci: build release & push artifact

---

.github/workflows/sonar.yml
build.gradle
eno-core/src/main/java/fr/insee/eno/core/model/variable/VariableGroup.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticLoopResolution.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/calculatedvariable/ShapefromAttributeRetrievalFromVariableGroups.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/calculatedvariable/ShapefromAttributeRetrievalFromVariableGroupsTest.java

The 'shapeFrom' Lunatic attribute was retrieved by getting the first collected variable in a variable group.
Yet, this information comes from DDI, and the list of variable references in a variable group is not ordered in DDI specification.
So, the previous implementation worked 'by chance' on most questionnaires (where variable references end up to be in the right order), but failed on questionnaires generatied with Pogues "composition" feature.
Instead of looking at the first variable of a variable group, the processing method now retrieves the corresponding main loop or dynamic table, and gets the first collected variable within that scope.
:warning: _Important note:_ the same rule as for linked loop "iterations" apply: **the first question of a main loop must be a simple question** …

fix: lunatic shape from

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIResolveVariableReferencesInExpressions.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/ddi/DDIResolveVariableReferencesInExpressionsTest.java

_(Reminder)_
1. In Pogues, the user inputs VTL expressions with variable names sourrounded with `$`.
2. In DDI, variable names are replaced with references.
3. In the Lunatic questionnaire, these references must be replaced by the corresponding variable names.
The issue: 
Variable references in DDI are a referrence suffixed with a number 1, 2, 3...
This could lead to an incorrect replacement in expressions that use 10 or more variables: 
`ref-10` could be replaced by `<name of variable "1">0`
Sort variable references in a certain way before replacing them in DDI "variable reference in expression resolution" processing.
---
Note: this is more tricky than it should be imo...
We may rework the DDI implementation of the references subject to make our lives easier 🙃

fix: ddi expression references resolution

---

eno-core/src/main/java/fr/insee/eno/core/model/question/Question.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddMissingVariables.java
eno-core/src/main/java/fr/insee/eno/core/utils/LunaticUtils.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddMissingVariablesPairwiseTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddMissingVariablesTest.java

- #875 
The "response" object was put instead of its "name" value.
Also updated to condition which differentiate the behavior between main loops and linked loops for the "missing" variables: the difference shouldn't be between main vs. linked loops, but between non paginated/paginated loops.
\+ refactor and add javadoc to make code clearer

fix: pairwise missing variable name

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/converter/LunaticConverter.java
eno-core/src/main/java/fr/insee/eno/core/model/variable/CalculatedVariable.java
eno-core/src/main/java/fr/insee/eno/core/model/variable/CollectedVariable.java
eno-core/src/main/java/fr/insee/eno/core/model/variable/ExternalVariable.java
eno-core/src/main/java/fr/insee/eno/core/model/variable/Variable.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddCleaningVariables.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddMissingVariables.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddShapeToCalculatedVariables.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticFilterResult.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticFinalizePairwise.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticVariablesValues.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticLoopResizingLogic.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticPairwiseResizingLogic.java
eno-core/src/main/java/fr/insee/eno/core/utils/LunaticUtils.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/CalculatedVariableTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/DynamicTableIntegrationTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/VariableTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddCleaningVariablesTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddMissingVariablesPairwiseTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddMissingVariablesTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddShapeToCalculatedVariablesTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticFilterResultTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticFinalizePairwiseTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticReverseConsistencyControlLabelTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticVariablesValuesTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticLoopResizingLogicTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticPairwiseResizingLogicTest.java
eno-core/src/test/java/fr/insee/eno/core/sandbox/LunaticTests.java
settings.gradle

Previous modeling of Luantic-Model variables allowed to serialize invalid variable objects (e.g. external variables with a `"values"` props).
- use new version of Lunatic-Model
- refactor with new variable objects
This fix issues like the `"values"` property appearing in calculated or external variables.

fix: lunatic variables serialization

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/model/label/DynamicLabel.java
eno-core/src/main/java/fr/insee/eno/core/parameter/LunaticParameters.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/LunaticProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticFilterResult.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticQuestionComponent.java
eno-core/src/main/java/fr/insee/eno/core/utils/LunaticUtils.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/CalculatedVariableTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/ComponentFilterTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/ControlRowTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/DetailResponseTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/LabelTests.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/MultipleChoiceQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/PairwiseQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/SimpleUniqueChoiceQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddControlFormatTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticInsertUniqueChoiceDetailsTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticLoopResolutionTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticQuestionComponentTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/table/ComplexMultipleChoiceQuestionProcessingTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/table/DynamicTableQuestionProcessingTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/table/TableQuestionProcessingTest.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/GenerationStandardController.java
settings.gradle

- #957 
Lunatic-DSFR introduced a `Question` component, which encapsulates response components such as Input, InputNumber, Table etc.
"Question" component feature:
- processing that wraps response components in `Question`
- add a `"dsfr"` parameter that activates this processing or not
- add a query param for this parameter in standard Lunatic generation controller `/questionnaire/{context}/lunatic-json/{mode}`
Refactor:
- remove usage of "FilterDescription" component which has been deleted in Lunatic-Model
- remove usage of `getTypeEnum() -> LabelTypeEnum` replaced by `getType() -> LabelTypeEnum` in Lunatic-Model

feat: lunatic dsfr question component

---

eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/ControlRowTest.java

- #1020 
- #1045
Actually fixed by:
- #1047 
The controls at row level in dynamic tables (roster for loop components in Lunatic) were mapped with the `"typeOfControl"` `"ROW"`.
These should instaed have `"typeofControl"` = `"CONSISTENCY"`, with a separate property `"type"` with the value `"ROW"`. The PR 1047 fixed this.
By rebound, this has also fixed the _inversion_ of these controls, since [the processing class that does it](https://github.com/InseeFr/Eno/blob/a205c2320aeed64b396ac8ff2ea57ce6063bb3b5/eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticReverseConsistencyControlLabel.java) filters controls that have the `typeOfControl` property equal to `CONSISTENCY`.
Added a test case for this.

test: lunatic dynamic table row control inversion

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticInsertUniqueChoiceDetails.java

When a questionnaire contains a roundabout that has a unique choice question in its components, the Lunatic generation fails.
The Lunatic processing step for detail responses tries to link Eno unique choice questions with the corresponding Lunatic component. The problem was that the function that makes this link didn't look in Lunatic roudabouts.
Also, this fix:
- improves this step to only process questions that actually have details responses, 
- and also makes detail responses in the pairwise component possible.

fix: update detail response processing with roundabout

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIMarkRoundaboutFilters.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoops.java
eno-core/src/main/java/fr/insee/eno/core/utils/VtlSyntaxUtils.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/ddi/DDIMarkRoundaboutFiltersTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoopsTest.java
eno-core/src/test/java/fr/insee/eno/core/utils/VtlSyntaxUtilsTest.java

In roundabouts, the "disabled" condition in Lunatic must be the same as the "_Sauf_" (_except_) condition inputted by the used in Pogues.
Yet this condition is inverted in the DDI.
At first, I inverted the "disabled" condition in the Lunatic processing that generates roundabout loops, but this would have needed refactor when doing the Pogues -> Lunatic transformation (since the condition is the same in both formats).
=> Inverted the filter expression of roundabout filters in a DDI processing (used the one that identify roundabout filters and marks them).

fix(roundabout): disabled condition

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/common/steps/EnoAddIdentificationSection.java
eno-core/src/main/java/fr/insee/eno/core/utils/LunaticUtils.java
eno-core/src/test/java/fr/insee/eno/core/processing/common/steps/EnoAddIdentificationSectionTest.java

Un oubli révélé par : 
- InseeFr/Public-Enemy-Back-Office#107
L'objet de réponse était manquant dans la question d' "identification" ajoutée pour les questionnaires en contexte "BUSINESS".

fix: response in identification question

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/DDIToLunatic.java
eno-core/src/main/java/fr/insee/eno/core/PoguesToEno.java
eno-core/src/main/java/fr/insee/eno/core/PoguesToLunatic.java
eno-core/src/main/java/fr/insee/eno/core/mappers/PoguesMapper.java
eno-core/src/main/java/fr/insee/eno/core/serialize/PoguesDeserializer.java
eno-ws/build.gradle
eno-ws/src/main/java/fr/insee/eno/ws/controller/GenerationCustomController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/GenerationPoguesController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/GenerationStandardController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/utils/EnoJavaControllerUtils.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/utils/EnoXmlControllerUtils.java
eno-ws/src/main/java/fr/insee/eno/ws/exception/DDIToLunaticException.java
eno-ws/src/main/java/fr/insee/eno/ws/exception/PoguesToLunaticException.java
eno-ws/src/main/java/fr/insee/eno/ws/service/DDIToLunaticService.java
eno-ws/src/main/java/fr/insee/eno/ws/service/LunaticGenerationService.java
eno-ws/src/main/java/fr/insee/eno/ws/service/PoguesToLunaticService.java
eno-ws/src/main/resources/application.properties
eno-ws/src/test/java/fr/insee/eno/ws/service/DDIToLunaticServiceTest.java

Create direct Pogues to Lunatic endpoints.
Rearranged API swagger documentation a bit.
Tiny fix on the way: generated DDI files from the poguesxml-2-ddi controller had the wrong name.

feat(ws): direct pogues to lunatic endpoints

---

src/main/resources/xslt/inputs/pogues-xml/source-fixed.xsl
src/main/resources/xslt/inputs/pogues-xml/templates.fods

- use RMéS address only for static units
- transform expression for dynamic units

manage dynamic unit

---

.github/workflows/test.yml
pom.xml
src/main/java/fr/insee/eno/transform/xsl/EnoErrorListener.java
src/main/java/fr/insee/eno/xsl/FodsToXSLCompiler.java
src/test/java/fr/insee/eno/test/TestDDI2FODT.java
src/test/java/fr/insee/eno/test/XMLDiff.java
src/test/resources/log4j2-test.xml

- fix jaxb dependency issues
- improve logging when tesing and building the lib
- update depdendencies cf. renovate

V2 next: 2.10.1

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/model/sequence/ItemReference.java
eno-core/src/test/java/fr/insee/eno/core/DDIToEnoTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoopsTest.java
eno-core/src/test/resources/functional/ddi/ddi-lx4qzdty.xml
eno-core/src/test/resources/functional/pogues/pogues-lx4qzdty.json
eno-core/src/test/resources/integration/ddi/ddi-roundabout-subsequence.xml

Pogues permet de définir un rondpoint sur une sous-séquence.
Ce cas n'était pas prévu dans le mapping du DDI et provoquait une exception.
NB : Cas découvert en travaillant sur les contrôles de rondpoints, cf : 
- https://github.com/InseeFr/Eno/issues/1121

fix: roundabout on subsequence

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/model/navigation/Control.java
eno-core/src/main/java/fr/insee/eno/core/model/sequence/RoundaboutSequence.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/DDIInProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIInsertControls.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIMarkRowControls.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoops.java
eno-core/src/main/java/fr/insee/eno/core/reference/EnoCatalog.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/ddi/ControlTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/ddi/DDIInsertControlsTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/ddi/DDIMarkRowControlsTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoopsTest.java
eno-core/src/test/resources/integration/ddi/ddi-roundabout-controls.xml
eno-core/src/test/resources/integration/pogues/pogues-roundabout-controls.json

- #1119 
Todo : j'ai la doc mais à intégrer et push
- #1120 
Questionnaire de test d'intégration `ddi-roundabout-controls.xml` et la source `pogues-roundabout-controls.json`
- #1121 
Il a fallu modifier les processing steps côté lecture DDI pour prendre en compte les control construct references des contrôles de rondpoint.
Plus léger sur la partie Lunatic où il a suffit de mapper les contrôles dans le composant `"Roundabout"` (fait en réutilisant le mapper).

feat: roundabout controls

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/model/sequence/RoundaboutSequence.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticReverseConsistencyControlLabel.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoops.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoopsTest.java

- https://github.com/InseeFr/Concevoir-Workplace/issues/41#issuecomment-2461818639
- Il y avait bien un problème sur la property Lunatic `locked` en présence de contrôles sur un rondpoint : la property était à `true` même si non cochée dans Pogues. La raison : cette information est modélisée comme un type spécial de contrôle en DDI, avoir d'autres contrôles a nécessité un mapping un peu plus fin pour ne pas mélanger ce type de contrôle avec les autres.
- Les contrôles sont inversés entre DDI et Lunatic, cette inversion n'était pas appliquée sur les contrôles de rondpoint. C'est corrigé.

fix: roundabout controls

---

eno-core/src/main/java/fr/insee/eno/core/utils/LunaticUtils.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticLoopResizingLogicTest.java

- #1157 
Les composants de type `DURATION` étaient ignorés dans la méthode des `LunaticUtils` qui va chercher la liste des réponses d'une boucle.
L'erreur était silencieuse car le cas `default` dans le switch d'une des méthodes se contentait d'un `log.debug` 😶 
---
**NB** : Les composants de type `SUGGESTER` étaient ignorés aussi. On avait donc le même bug pour les suggester saisis depuis Pogues dans une boucle. Mais ça ne concerne pas les suggester créés avec un traitement spécifique (le cas le plus utilisé aujourd'hui encore j'imagine).
C'est corrigé au passage.

fix: duration components in resizing

---

eno-core/src/main/java/fr/insee/eno/core/model/code/CodeList.java
eno-core/src/main/java/fr/insee/eno/core/model/question/Question.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIInsertMultipleChoiceLabels.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/ddi/DDIInsertMultipleChoiceLabelsTest.java

cf.
- https://github.com/InseeFr/Pogues/issues/883
Quand une liste de code utilisée dans une question a choix multiples a plus de codes que la question à choix multiple n'a de réponses, on avait une exception assez générique `IndexOutOfBoundsException` avec un message pas suffisamment précis pour comprendre l'origine de l'erreur.
Ajout d'une vérification sur la taille des deux listes, renvoi d'une exception si les deux diffèrent.

refactor: improve exception handling in ddi insert labels step

---

pom.xml
src/main/resources/xslt/inputs/pogues-xml/functions.fods
src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/functions.fods

- dynamic unit in Pogues to DDI
- dependencies update

V2 next: 2.12.0

---

pom.xml
src/main/resources/xslt/outputs/ddi/models.xsl

cf. 
- https://github.com/InseeFr/Eno/pull/1155#issuecomment-2536598796

fix(dynamic unit): controlledVocabularyName attribute

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/model/question/NumericQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/table/NumericCell.java
eno-core/src/main/java/fr/insee/eno/core/model/variable/Variable.java
eno-core/src/main/java/fr/insee/eno/core/processing/common/steps/EnoAddResponseTimeSection.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/DDIInProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIMoveUnitInQuestions.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticEditLabelTypes.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticInputNumberDescription.java
eno-core/src/main/java/fr/insee/eno/core/reference/EnoCatalog.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/ddi/VariableTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/NumberQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/ddi/DDIMoveUnitInQuestionsTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticInputNumberDescriptionTest.java
eno-core/src/test/resources/integration/ddi/ddi-dynamic-unit.xml
eno-core/src/test/resources/integration/pogues/pogues-dynamic-unit.json
settings.gradle.kts

feat(ddi to lunatic): dynamic units

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIInsertControls.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIMarkRowControls.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/ddi/DDIInsertControlsTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/ddi/DDIMarkRowControlsTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoopsTest.java
eno-core/src/test/resources/integration/ddi/ddi-roundabout-except.xml
eno-core/src/test/resources/integration/pogues/pogues-roundabout-except.json

Quand un rondpoint a un filtre d'occurrences (champ "sauf" dans l'interface de création d'un rondpoint dans Pogues), ses contrôles d'occurrences n'apparaissaient pas dans le questionnaire Lunatic.
Corrigé par cette PR

fix: roundabout with except

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticAddResizing.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticLoopResizingLogic.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticRosterResizingLogic.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticRosterResizingLogicTest.java

Avant, la taille des tableaux dynamiques était définie par des valeurs fixes min/max.
Depuis : 
- #1148
la taille d'un tableau dynamique peut être définie par une expression VTL.
Comme pour les boucles, il faut que si une variable impliquée dans le calcul de la taille du tableau change, alors les variables qui appartiennent au tableau soient redimensionnées : c'est le bloc `"resizing"` généré dans le questionnaire Lunatic qui assure cela, et ça avait était oublié dans la PR mentionnée ci-dessus
@alicela @loichenninger @alexisszmundy pour info, mais hésitez pas à review si le coeur vous en dit 🙃

fix(dynamic table): resizing for size expression

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoops.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoopsTest.java
eno-core/src/test/resources/integration/ddi/ddi-roundabout.xml
eno-core/src/test/resources/integration/pogues/pogues-roundabout.json

Comme pour les séquences, Pogues permet à l'utilisateur de saisir des déclarations dans un rondpoint.
Ces déclarations étaient ignorées dans la transformation DDI vers Lunatic.
À l'instar de ce qui est fait pour les séquences, j'ai transformé la déclaration saisie dans Pogues en description du composant rondpoint.
Question Lunatic : j'ai mis le type de la description en `VTL_MD`, c'est ok @laurentC35 @QRuhier ?
Doc DDI sur le rondpoint (il y a des types d'instructions particuliers dans le rondpoint, je suis pas mécontent d'avoir fait cette doc pour ce coup là 😄 ) https://inseefr.github.io/ddi-questionnaire-modeling/roundabout/
rappel du vocabulaire DDI : 
- _Instruction_ = déclaration saisie dans Pogues pour l'enquêté (concrètement c'est une déclaration "après la question")
- …

fix: roundabout description

---

eno-core/src/main/java/fr/insee/eno/core/exceptions/business/IllegalPoguesElementException.java
eno-core/src/main/java/fr/insee/eno/core/model/EnoQuestionnaire.java
eno-core/src/main/java/fr/insee/eno/core/model/label/QuestionnaireLabel.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/pogues/PoguesCheckExpressionLanguage.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/pogues/PoguesCheckFilterMode.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/EnoQuestionnaireTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/pogues/PoguesCheckExpressionLanguageTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/pogues/PoguesCheckFilterModeTest.java
eno-core/src/test/resources/integration/ddi/ddi-simple.xml
eno-core/src/test/resources/integration/pogues/pogues-simple.json

Mapping des propriétés de niveau questionnaire de Pogues vers Eno.
J'ai utilisé les propriétés "flowLogic" et "formulasLanguage" pour contrôler qu'Eno java n'est pas appelé avec un questionnaire en "go to" (déprécié) ou en "xpath" (pas de génération autre que Lunatic dans Eno java pour l'instant). Pas indispensable mais une sécurité qui peut pas faire de mal.

feat(pogues mapping): questionnaire properties

---

eno-core/src/main/java/fr/insee/eno/core/model/question/DateQuestion.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/DateQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/ddi/DateQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/DynamicTableQuestionTest.java
eno-core/src/test/resources/integration/ddi/ddi-dates-2.xml
eno-core/src/test/resources/integration/pogues/pogues-dates-2.json

Mapping des infos des questions de type date de Pogues.
NB pour la partie tests : JUnit ne propose pas de test paramétrés avec les annotations `@BeforeEach`/`@BeforeAll`, pas d'autre choix que de templatiser avec une classe abstraite faire un `@BeforeAll` avec DDI d'un côté, Pogues de l'autre.

feat(pogues mapping): date questions

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/PoguesDDIToEno.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/GenerationCustomController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/GenerationPoguesController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/GenerationStandardController.java
eno-ws/src/main/java/fr/insee/eno/ws/service/DDIToFOService.java
eno-ws/src/main/java/fr/insee/eno/ws/service/LunaticGenerationService.java
eno-ws/src/main/java/fr/insee/eno/ws/service/PoguesToDDIService.java
eno-ws/src/main/java/fr/insee/eno/ws/service/PoguesToLunaticService.java
eno-ws/src/main/java/fr/insee/eno/ws/service/SpecificTreatmentsService.java
eno-ws/src/test/java/fr/insee/eno/ws/service/DDIToLunaticServiceTest.java

Modification de la classe de service `PoguesToLunaticService` pour faire : 
- "Pogues to Lunatic" direct si la property qui correspond est à true
- sinon "Pogues to DDI" avec Eno Xml, puis "Pogues + DDI to Lunatic"
c'était l'occasion de déporter cette logique qui était côté _controller_
Comme certaines fonctionnalités ne sont pas complètement décrites en DDI, la transformation "DDI to Lunatic" est désormais dépréciée côté web-service Eno.

feat(eno-ws): pogues plus ddi transformation

---

eno-core/src/main/java/fr/insee/eno/core/PoguesDDIToEno.java
eno-core/src/main/java/fr/insee/eno/core/converter/PoguesMultipleChoiceQuestionConverter.java
eno-core/src/main/java/fr/insee/eno/core/converter/PoguesSingleResponseQuestionConversion.java
eno-core/src/main/java/fr/insee/eno/core/mappers/InMapper.java
eno-core/src/main/java/fr/insee/eno/core/mappers/LunaticMapper.java
eno-core/src/main/java/fr/insee/eno/core/mappers/Mapper.java
eno-core/src/main/java/fr/insee/eno/core/model/EnoQuestionnaire.java
eno-core/src/main/java/fr/insee/eno/core/model/calculated/CalculatedExpression.java
eno-core/src/main/java/fr/insee/eno/core/model/navigation/ComponentFilter.java
eno-core/src/main/java/fr/insee/eno/core/processing/common/steps/EnoResolveBindingReferences.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/PoguesInProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIInsertCodeLists.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIResolveSequencesStructure.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIResolveVariableReferencesInExpressions.java
eno-core/src/test/java/fr/insee/eno/core/DDIToEnoTest.java
eno-core/src/test/java/fr/insee/eno/core/PoguesDDIToEnoTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/DynamicTableQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/TableQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/ddi/DDIInsertCodeListsTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/ddi/DDIResolveVariableReferencesInExpressionsTest.java
eno-core/src/test/resources/functional/ddi/ddi-l8x6fhtd.xml
eno-core/src/test/resources/functional/pogues/pogues-kzy5kbtl.json
eno-core/src/test/resources/functional/pogues/pogues-l20g2ba7.json
eno-core/src/test/resources/functional/pogues/pogues-l5v3spn0.json
eno-core/src/test/resources/functional/pogues/pogues-l8x6fhtd.json
eno-core/src/test/resources/functional/pogues/pogues-li49zxju.json
eno-core/src/test/resources/functional/pogues/pogues-ljr4jm9a.json
eno-core/src/test/resources/integration/ddi/ddi-suggester-arbitrary.xml
eno-core/src/test/resources/integration/pogues/pogues-suggester-arbitrary.json
settings.gradle.kts

Problématique / contexte : 
1. Pogues mapping
1. DDI mapping
1. Lunatic mapping
-> On veut pouvoir lire certaines infos présentes dans l'input Pogues et pas en DDI, mais quand même lire le DDI car le mapping Pogues est incomplet.
Avant cette PR, les objets DDI écrasaient ceux de Pogues, donc on perdait les infos spécifiques à Pogues 😿 
Refactor/fixes pour garder les objets qui viennent de Pogues, en sécurisant le processus pour que le mapping préalable Pogues ne "déforme" pas le mapping DDI.

fix: pogues plus ddi mapping

---

pom.xml
src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/test/java/fr/insee/eno/test/TestPoguesXMLToDDI.java
src/test/resources/pogues-xml-to-ddi/suggester-arbitrary/in-loop.xml
src/test/resources/pogues-xml-to-ddi/suggester-arbitrary/in.xml
src/test/resources/pogues-xml-to-ddi/suggester-arbitrary/out-loop.xml
src/test/resources/pogues-xml-to-ddi/suggester-arbitrary/out.xml

La réponse "champ libre" pour les questions à choix unique en auto-complétion (réponse _aribitrary_ pour les _suggesters_) n'est pas modélisée en DDI.
Cependant il faut que la variable associée à la réponse _arbitrary_ soit créée dans le DDI, et mise dans le bon `VariableGroup`.
Dans `inputs/pogues-xml`
- ajustements XPath pour que la présence de la variable arbitrary (qui est associée à une `ArbitraryResponse` et pas une `Response` comme les autres collectées) ne fasse pas planter la transfo (erreurs du style _An empty sequence is not allowed as the first argument of is-not-collected_)
- ajout de `ArbitraryResponse` à côté de `Response` dans certains templates
_**To do**_ : ajouter ce qu'il faut pour que la variable arbitrary soit référencée dans un `VariableGroup` dans DDI

fix(pogues2ddi): arbitrary response

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/mappers/InMapper.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/PoguesInProcessing.java

Processing step de Pogues pour les detail responses appellée à tort.
\+ truc tricky : les detail responses en DDI sont décrites comme des réponses ordinaires => nécessité d'ajouter une exception dans `InMapper` pour autoriser le fait d'avoir des listes de taille différente entre Pogues et DDI pour les `codeResponses` des QCM "tableau"

fix: detail responses bug

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/converter/PoguesMultipleChoiceQuestionConverter.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/DynamicTableQuestionTest.java

Exception levée pendant le mapping Pogues en présence de tableaux dynamiques de taille définie en VTL.
NB : ça ferait pas de mal de refacto la prop qui définit le "type" des "dynamic" des tableaux Pogues en enum plutôt que du string...

fix(pogues): conversion error for vtl size tables

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/mappers/InMapper.java
eno-core/src/test/java/fr/insee/eno/core/PoguesDDIToEnoTest.java
eno-core/src/test/resources/integration/ddi/ddi-other-specify.xml
eno-core/src/test/resources/integration/pogues/pogues-controls-line.json
eno-core/src/test/resources/integration/pogues/pogues-dimensions.json
eno-core/src/test/resources/integration/pogues/pogues-dynamic-table-2.json
eno-core/src/test/resources/integration/pogues/pogues-dynamic-table.json
eno-core/src/test/resources/integration/pogues/pogues-no-data-cell.json
eno-core/src/test/resources/integration/pogues/pogues-other-specify.json
eno-core/src/test/resources/integration/pogues/pogues-suggester-options-table.json
eno-core/src/test/resources/integration/pogues/pogues-suggester.json
eno-core/src/test/resources/integration/pogues/pogues-tooltips.json
eno-ws/src/main/java/fr/insee/eno/ws/controller/GenerationCustomController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/GenerationStandardController.java

- test: add non-regression tests for the Pogues+DDI inputs mapping
- fix: temporary remove the inconsistency list size check for the `variables` property of Eno questionnaire
- The reason is that table "no data cells" have collected variables in the Pogues questionnaire that get filtered in DDI in the Eno Xml Pogues to DDI transformation. 
- To do in a next PR: add a Pogues processing that does this filtering and restore the check.
- refactor: remove the "disabled" tag on DDI to Lunatic generation endpoints while users are not familiar with generation of questionnaire from Pogues

hotfix: no data cell variables

---

pom.xml
src/main/resources/params/default/parameters.xml
src/test/java/fr/insee/eno/test/TestDDI2FO.java
src/test/resources/ddi-to-fo/out.fo

Changement du paramétrage pour les pdf générés : 
- Moins de boucles par défaut.
- Moins de lignes dans les tableaux dynamiques par défaut.
- Saisie manuelle au lieu de la lecture optique.

refactor: default params papi

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/model/calculated/CalculatedExpression.java
eno-core/src/main/java/fr/insee/eno/core/model/label/DynamicLabel.java
eno-core/src/main/java/fr/insee/eno/core/model/label/Label.java
eno-core/src/main/java/fr/insee/eno/core/serialize/PoguesDeserializer.java
eno-core/src/test/java/fr/insee/eno/core/PoguesDDIToEnoTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/NumericQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/CalculatedExpressionTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/DynamicLabelTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/LabelTest.java
eno-ws/src/main/java/fr/insee/eno/ws/EnoWsApplication.java

- Correction sur les `$` dans les libellés VTL avec le questionnaire Pogues en input (PR en cours)
Autres :
- Refacto sur le PoguesDeserializer pour ne pas utilisée une méthode dépréciée.

v3-next: 3.36.1

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/mappers/InMapper.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/CalculatedExpressionTest.java
eno-core/src/test/resources/integration/ddi/ddi-ghost-variables.xml
eno-core/src/test/resources/integration/pogues/pogues-ghost-variables.json

La présence de variables inconnues / fantômes dans les questionnaires Pogues provoquait une exception.
Corrigé en retirant la sécurité de "listes de même taille entre Pogues & DDI" pour la property `bindingReferences` du modèle Eno qui contient les références de variables dans les formules.

fix(pogues mapping): ghost variables error

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/parameter/LunaticParameters.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/LunaticProcessing.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/GenerationStandardController.java

Ajout d'un paramètre **questionWrapping** avec les valeurs : 
- **true [default value]** : génère un lunatic model avec le composant question.
- **false :** génère un lunatic model sans le composant question.
👍 Pour deux endpoints des standard parameters (**/questionnaire/{context}/lunatic-json/{mode}** et /**questionnaire/pogues-2-lunatic/{context}/{mode}**)
💯 _Une description a été ajoutée dans le Swagger à côté du paramètre pour indiquer qu'il est temporaire._

Feat: adding parameter question wrapping

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/model/question/SingleResponseQuestion.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/LunaticProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticDateDescription.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticDurationDescription.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/control/LunaticDatepickerControl.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/MandatoryQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddControlFormatTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticDateDescriptionTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticDurationDescriptionTest.java
eno-core/src/test/resources/integration/pogues/pogues-pairwise.json

1) Implémentation de la logique pour afficher des repères visuels au niveau des dates (aide à la saisie des dates) : indications min/max. 
**4 cas :** 
- **Si min et max :** on affiche **"Entre min et max."**
- **Si min et pas de max :** on affiche **"Après min."**
- **Si max et pas de min :** on affiche **"Avant max."**
- **Si pas de min et pas de max :** on n'affiche rien.
2) Suppression des contrôles sur les années pour les dates.
+ Ajout/suppression de tests.

Feat: reperes saisie dates

---

.github/workflows/create-release.yml
.github/workflows/create-snapshot.yml

Simplification des workflows de déploiement ~~& automatisation de la gestion du numéro de version~~.
EDIT: j'ai pas trouvé/réussi à faire marche de GitHub action pour calculer le numéro de version à partir des conventional commits, j'ai juste préparé le terrain pour faire du semantic versioning plus tard
- **pour les snapshots**: on touche pas à la version, la ci publie une image `<version actuelle>-<sha short du last commit>` : simple, on sait sur quelle version de main on build, et pas d'ambiguïté sur où en est la "snapshot" déployée
- _pourquoi ce choix ?_ le problème qu'on avait c'est que dans les cas où on bosse en parallèle, le semver sur les "SNAPSHOT" était souvent incohérent entre les branches qui se voient pas forcément les unes avec les autres
- \+ j'aime bien ne pas polluer le …

ci: semantic versioning

---

build.gradle.kts

A noter l'avertissement sur le passage à tomcat 10.1.42 qui introduit une limitation sur les requêtes `multipart/form-data` : à vérifier si ça ne casse pas quelque chose.
cf. https://github.com/spring-projects/spring-boot/releases/tag/v3.5.1

fix(spring): issue in tomcat embedded dependency

---

eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticLoopResolution.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticLoopResizingLogic.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticRosterResizingLogic.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/table/DynamicTableQuestionProcessing.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticLoopResolutionTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticAddResizingTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticLoopResizingLogicTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticRosterResizingLogicTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/table/DynamicTableQuestionProcessingTest.java

- l'`iterations` est désormais calculée en fonction des variables collectée lorsque (min!=max) (il s'agisait d'un oubli au niveau du composant Question)
- suppression de code
- adaptation des tests
- on retire la logique de resizing lorsque min != max pour les boucles et tableaux dynamique
- adaptation de la logique de resizing
- adaptation des tests
- Correction: Affichage des tableaux min <> max VTL
- Correction: Boucles non paginées, on affiche la bonne taile
=> évite des pertes de données au re-chargement du formulaire lunatic (resize par le bas)
https://github.com/InseeFr/Lunatic/pull/1266

fix: iteration & resising logic

---

src/main/resources/xslt/outputs/fo/models.xsl
src/test/resources/ddi-to-fo/out.fo
src/test/resources/params/in-to-out/business/form.fo

La mise en forme des nombres potentiellement à personnaliser était perdue
C'était un bug...
La fonction concat transforme les structures XML pour ne conserver que le texte qu'elles contiennent.
Un concat était utilisé à tort...

fix(paper): mise en forme des nombres potentiellement à personnaliser

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/converter/LunaticConverter.java
eno-core/src/main/java/fr/insee/eno/core/model/EnoQuestionnaire.java
eno-core/src/main/java/fr/insee/eno/core/model/navigation/EnoArticulation.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/LunaticProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticArticulationSource.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/ArticulationIntegrationTest.java
eno-core/src/test/resources/integration/ddi/ddi-articulation.xml
eno-core/src/test/resources/integration/pogues/pogues-articulation.json
settings.gradle.kts

Articulation feature. The idea is to have a kind of recap component in Lunatic, so that if the questionnaire is transferred (self-administred to a interviewer for instance), there is a recap showing the individuals of the questionnaire.
Mapping from Pogues to Lunatic.
Note: this feature is not described in DDI.

feat: articulation

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticLoopResolution.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticReverseConsistencyControlLabel.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/loop/LunaticLoopFilter.java
eno-core/src/main/java/fr/insee/eno/core/utils/vtl/VtlSyntaxUtils.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticLoopResolutionTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoopsTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/shapefrom/LunaticHierarchyShapeFromTest.java

Le problème : Eno décidait que la condition filter d'une boucle était la condition filter de son premier composant (qui est une séquence ou une sous-séquence).
_Exemple de cas qui pose problème_ : 
- boucle sur deux séquences
- sur la première filtre "TOTO = 1"
- sur ma deuxième filtre "TOTO = 0"
- => Filtre sur le composant boucle "TOTO = 1"
- => dans un des cas les deux séquences se retrouvent filtrées, alors qu'on devrait voir la deuxième
Note : le problème est présent depuis (très) longtemps (a priori depuis la première release de prod d'Eno java).

fix: lunatic loop filter
