InseeFr/Eno

questionnaires/simpsons/parameters.xml
src/main/xslt/util/ddi/titling.xsl

2nd update of step 4 containing : 
- Fix on question -> Question in parameters.xml
- Fix in titling.xsl : UpperCamelCase on NumberFreeSeq and NotNumberedLastFilter

Step 4 Second review

---

questionnaires/simpsons/ddi/simpsons-ccs.xml
questionnaires/simpsons/ddi/simpsons-qb.xml
questionnaires/simpsons/parameters.xml
src/main/xslt/inputs/ddi/source-fixed.xsl
src/main/xslt/inputs/ddi/templates.fods
src/main/xslt/transformations/ddi2fr/drivers.fods
src/main/xslt/transformations/ddi2fr/tree-navigation.fods
src/main/xslt/util/ddi/cleaning.xsl
src/main/xslt/util/ddi/dereferencing.xsl
src/main/xslt/util/ddi/titling.xsl

First Pull Request concerning the step 6 of the internationalization process.
Contains : 
- All previous steps up-to-date
- The new input files (ccs and qb)
- Updated files to match with the new requirements : 
- templates.fods
- drivers.fods
- tree-navigation.fods
- source-fixed.xsl
- titling.xsl
- dereferencing.xsl
- cleaning.xsl
- Added comments in templates.fods and inputs/functions.fods

Internationalization : Step 6

---

questionnaires/simpsons/parameters.xml
src/main/config/config.properties
src/main/scripts/build-configuration.xml
src/main/scripts/build-non-regression.xml
src/main/xslt/inputs/ddi/source-fixed.xsl
src/main/xslt/inputs/ddi/templates.fods
src/main/xslt/inputs/fods/source.xsl
src/main/xslt/inputs/xml/source.xsl
src/main/xslt/outputs/fr/models.xsl
src/main/xslt/outputs/xml/models.xsl
src/main/xslt/outputs/xsl/basic-copy.xsl
src/main/xslt/outputs/xsl/init-rep.xsl
src/main/xslt/outputs/xsl/models.xsl
src/main/xslt/transformations/ddi2fr/ddi2fr-fixed.xsl
src/main/xslt/transformations/ddi2fr/drivers.fods
src/main/xslt/transformations/ddi2fr/functions.fods
src/main/xslt/transformations/fods2xml.xsl
src/main/xslt/transformations/xml2xsl.xsl
src/main/xslt/util/ddi/cleaning.xsl
src/main/xslt/util/ddi/dereferencing.xsl
src/main/xslt/util/ddi/titling.xsl
src/main/xslt/util/fods/preformatting.xsl
src/main/xslt/util/xsl/incorporation.xsl

Updated step 6 (for parameters.xml and titling.xsl).
Added the first delivery of the documentation, concerning src/main/config, scripts and xml folders.

Step 6 : updated + First documentation delivery

---

src/main/resources/xslt/inputs/pogues-xml/functions.fods
src/main/resources/xslt/inputs/pogues-xml/functions.xsl
src/main/resources/xslt/inputs/pogues-xml/source.xsl
src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/inputs/pogues-xml/templates.xsl
src/main/resources/xslt/outputs/ddi/models-real.xsl
src/main/resources/xslt/outputs/ddi/models-test.xsl
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/drivers.fods
src/main/resources/xslt/transformations/pogues-xml2ddi/functions.fods
src/main/resources/xslt/transformations/pogues-xml2ddi/functions.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/pogues-xml2ddi.xsl

with ENO-Core, by Eric Churlet, Antoine Dreyer, Eric Sigaud, Benoît Werquin.

First working version for Pogues-XML to DDI 3.2 transformation

---

src/main/resources/xslt/inputs/pogues-xml/functions.fods
src/main/resources/xslt/inputs/pogues-xml/source.xsl
src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/inputs/pogues-xml/templates.xsl
src/main/resources/xslt/outputs/ddi/models-real.xsl
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/drivers.fods
src/main/resources/xslt/transformations/pogues-xml2ddi/drivers.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/functions.fods
src/main/resources/xslt/transformations/pogues-xml2ddi/pogues-xml2ddi.xsl
src/main/resources/xslt/util/ddi/cleaning - old.xsl
src/main/resources/xslt/util/ddi/dereferencing-old.xsl
src/main/resources/xslt/util/ddi/dereferencing.xsl
src/main/resources/xslt/util/ddi/splitting.xsl
src/main/resources/xslt/util/ddi/title-parameters.xml
src/main/resources/xslt/util/ddi/titling-old.xsl
src/main/resources/xslt/util/ddi/titling.xsl
src/main/resources/xslt/util/pogues-xml/1Pogues-XML-preprocessing-new.xsl
src/main/resources/xslt/util/pogues-xml/2suppressionGoto.xsl
src/main/scripts/build-non-regression-DDIToFR.xml
src/main/scripts/build-non-regression-PogueToDDI.xml
src/main/scripts/build-non-regression-newDDI2FR.xml

Eric Churlet and Antoine Dreyer
Added documentation (more is still needed) ; added new dereferencing and new titling ; and other fixes to make it work. ANT scripts do not look good.
All of the chain is working from Pogues-XML to XForms, with excellent performance (probably nearly instant with right architecture).

Pogues-XML to DDI working version 2017-08-29

---

src/main/resources/xslt/inputs/ddi/source-fixed.xsl
src/main/resources/xslt/outputs/fr/models.xsl
src/main/resources/xslt/transformations/ddi2fr/ddi2fr-fixed.xsl
src/main/resources/xslt/transformations/ddi2fr/tree-navigation.fods
src/main/resources/xslt/util/ddi/dereferencing.xsl

Unuseful commented code suppressed.
Informational comments added.

comments added ; commented code removed

---

src/main/resources/xslt/inputs/ddi/templates.fods

Add a label for Response in grids...

Xforms prod

---

src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/util/ddi/mw2xhtml.xsl
src/main/resources/xslt/util/ddi/tweak-xhtml-for-ddi.xsl
src/main/scripts/build-pogues-xml2ddi.xml
src/test/resources/pogues-xml-to-ddi/out.xml

Fixing bugs in :
* mw transformation
* version handling
* sourceQuestion handling
* footnote

pogues-xml2ddi : several bug fixes

---

src/main/resources/xslt/inputs/ddi/functions.fods
src/main/resources/xslt/inputs/ddi/source-fixed.xsl
src/main/resources/xslt/inputs/ddi/templates.fods
src/main/resources/xslt/outputs/fr/models.xsl
src/main/resources/xslt/transformations/ddi2fr/ddi2fr-fixed.xsl
src/main/resources/xslt/transformations/ddi2fr/drivers.fods
src/main/resources/xslt/transformations/ddi2fr/functions.fods
src/main/resources/xslt/transformations/ddi2fr/tree-navigation.fods
src/main/resources/xslt/transformations/ddi2pdf/ddi2pdf-fixed.xsl
src/main/resources/xslt/transformations/ddi2pdf/drivers.fods
src/main/resources/xslt/transformations/ddi2pdf/functions.fods
src/main/resources/xslt/transformations/ddi2pdf/tree-navigation.fods
src/main/resources/xslt/util/ddi/dereferencing.xsl
src/test/resources/ddi-to-xform/out.xhtml

New driver to manage a very old problem, that made impossible to manage tooltips with id.

Single-response-question

---

src/main/resources/xslt/outputs/pdf/models.xsl

Nettoyage et paramétrage du fichier models.xsl

corrections Models.xsl 

---

Eno.xpr
src/main/resources/xslt/outputs/fr/models.xsl
src/main/resources/xslt/outputs/pdf/models.xsl
src/main/resources/xslt/transformations/ddi2fr/drivers.fods
src/main/resources/xslt/transformations/ddi2pdf/drivers.fods
src/main/resources/xslt/util/ddi/dereferencing.xsl
src/test/resources/ddi-to-fo/out.fo

For ddi2pdf and ddi2fr :
- creation of drivers DurationDomain and DateTimeDomain from DoubleDuration and part of xf-input
- enlargement of drivers DurationDomain and DateTimeDomain to all formats
TODO : evolution of drivers for ddi2odt and ddi2js

Date duration

---

src/main/resources/xslt/outputs/fr/models.xsl
src/main/resources/xslt/outputs/pdf/models.xsl
src/main/resources/xslt/transformations/ddi2fr/ddi2fr-fixed.xsl
src/main/resources/xslt/transformations/ddi2fr/drivers.fods
src/main/resources/xslt/util/pogues-xml/goto-2-if-then-else.xsl
src/test/resources/ddi-to-xform/out.xhtml

- refactor drivers : NumericDomain instead of part of xf-input
- If example necessary : //NumericExample = 'YES'

no numeric example

---

src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/util/pogues-xml/goto-2-if-then-else.xsl
src/main/scripts/build-pogues-xml2ddi.xml

- change ant call
- correct namespace problem
- use FlowControl id + start-element id in ITE r:ID
TODO : change Java call

Goto2ITe : werewolf version

---

src/main/resources/xslt/util/pogues-xml/goto-2-if-then-else.xsl

- bug with comments in xml-pogues
- bug when an overlap goes out from a sequence

Goto2ITE : new version

---

src/main/resources/xslt/outputs/pdf/models.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/pogues-xml2ddi-fixed.xsl
src/main/resources/xslt/util/pogues-xml/goto-2-if-then-else.xsl

- fo : bug response image in table with border
- Goto2ITE :
- stop-position : number instead of text
- before + To = 'last' : forgotten case (including before + from = last sibling)
- split cases : going out from's sequence and going out from's other ancestors sequence
- pogues2ddi : new case : sequence without Child (only IfThenElse)

bug fo + Goto2ITE

---

src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/drivers.fods
src/test/resources/pogues-xml-to-ddi/out.xml

Eno : commit 3efb217526bb611d54dc4425263971c24152b959
273B-BO Manage Date and Duration format when transform Pogues-xml2ddi

273B-BO Manage Date and Duration format when transform Pogues-xml2ddi

---

src/main/resources/xslt/outputs/fr/models.xsl
src/main/resources/xslt/util/fr/browsing.xsl
src/test/resources/ddi-to-xform/out.xhtml

- bug with filtered dynamic arrays
- but with loop of pages becoming blocking with Orbeon update
- improve parameters for the list of CSS :
- in the property file : several CSS files instead of 1
- in the parameter file :  additional CSS files

bug Coltrane + Orbeon update

---

src/main/resources/xslt/inputs/pogues-xml/functions.fods
src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/drivers.fods
src/main/resources/xslt/transformations/pogues-xml2ddi/functions.fods
src/test/resources/pogues-xml-to-ddi/out.xml

287 amelioration date duration pogues xml2ddi

---

src/main/resources/xslt/outputs/ddi/models.xsl
src/test/resources/pogues-xml-to-ddi/out.xml

288 mandatory responses

---

src/main/resources/xslt/outputs/fr/models.xsl
src/main/resources/xslt/util/fr/browsing.xsl
src/test/resources/ddi-to-xform/out.xhtml

Bug Ecmoss due to Orbeon's update : new debug

Bug Ecmoss due to Orbeon's update : new debug

---

src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/test/resources/pogues-xml-to-ddi/out.xml

290 version number pogues xml2ddi

---

src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/functions.fods
src/main/resources/xslt/transformations/pogues-xml2ddi/pogues-xml2ddi-fixed.xsl
src/main/resources/xslt/util/ddi/tweak-xhtml-for-ddi.xsl
src/test/resources/pogues-xml-to-ddi/out.xml

289 migration ddi v3 3

---

src/main/resources/xslt/outputs/js/models.xsl
src/main/resources/xslt/util/js/sort-components.xsl
src/test/resources/ddi-to-js/out.xml

- renaming : Checkbox -> CheckboxGroup
- options attribute becomes responses in CheckboxGroup
- add id attribute in components in cells

ddi2js : changing the model for Checkbox

---

src/main/resources/xslt/util/pdf/accompanying-mails/accompagnementCOL.fo
src/main/resources/xslt/util/pdf/accompanying-mails/cnrCOL.fo
src/main/resources/xslt/util/pdf/accompanying-mails/entreeCOL.fo
src/main/resources/xslt/util/pdf/accompanying-mails/medCOL.fo
src/main/resources/xslt/util/pdf/accompanying-mails/ouvertureCol.fo
src/main/resources/xslt/util/pdf/accompanying-mails/relanceCOL.fo

Update variable name : $BddAdresseMessagerieServiceCollecteur into $BddServiceCollecteurAdresseMessagerie

Coltrane accompanying mails

---

src/main/resources/xslt/outputs/ddi/models.xsl
src/test/resources/pogues-xml-to-ddi/out.xml

287bis bo modifications formules dates maximales

---

src/main/resources/xslt/outputs/ddi/models.xsl

288-Bis Fix Date and Duration MaximumResponses

---

src/main/java/fr/insee/eno/Constants.java
src/main/java/fr/insee/eno/generation/IdentityGenerator.java
src/main/java/fr/insee/eno/preprocessing/DDI32ToDDI33Preprocessor.java
src/test/java/fr/insee/eno/main/DummyTestDDI32ToDDI33.java
src/test/resources/ddi32-to-ddi33/in.xml

- add identity generator
- add PreProcessing (ddi32Toddi33)
- add path to xslSheet in Constants

ddi33 : java  implementation of ddi32Toddi33 transformation

---

questionnaires/simpsons/ddi/simpsons.xml
src/test/resources/ddi-to-fo/in.xml
src/test/resources/ddi-to-fo/out.fo
src/test/resources/ddi-to-xform/in.xml
src/test/resources/ddi-to-xform/out.xhtml

in.xml file becomes a copy from xml-pogues2ddi\out.xml file

update simpsons questionnaire for Xforms and pdf

---

src/main/resources/lang/fr/en.xml
src/main/resources/lang/fr/fr.xml
src/main/resources/xslt/inputs/ddi/source-fixed.xsl
src/main/resources/xslt/outputs/fr/models.xsl
src/main/resources/xslt/transformations/ddi2fr/ddi2fr-fixed.xsl
src/test/resources/ddi-to-xform/out.xhtml

It must be Orbeon's current date, not Eno's one

bug with current-date in XForms generation

---

src/main/java/fr/insee/eno/generation/DDI2ODTGenerator.java
src/main/resources/xslt/outputs/odt/models.xsl
src/main/resources/xslt/outputs/odt/office-styles.xsl
src/test/java/fr/insee/eno/test/TestDDIToODT.java
src/test/resources/ddi-to-odt/in.xml
src/test/resources/ddi-to-odt/out.fodt

add nameOfVariable in questions fields

Ddi33 : ddi2odt, nameOfVariable

---

src/main/resources/xslt/outputs/ddi/models.xsl
src/test/resources/pogues-xml-to-ddi/out.xml

299 populate external variables

---

src/main/resources/xslt/outputs/ddi/models.xsl

192 bo add new duration format hh ch

---

src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/pogues-xml2ddi-fixed.xsl
src/test/resources/pogues-xml-to-ddi/out.xml

301 bo populate calculated variable

---

src/main/resources/lang/fr/fr.xml
src/main/resources/xslt/outputs/fr/models.xsl
src/main/resources/xslt/transformations/ddi2fr/ddi2fr-fixed.xsl

Duration HH:CH :
- use minimum and maximum
- add message when CH and not HH

duration HH:CH : add constraint when CH and not HH

---

src/main/resources/xslt/inputs/pogues-xml/functions.fods
src/main/resources/xslt/inputs/pogues-xml/source-fixed.xsl
src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/drivers.fods
src/main/resources/xslt/transformations/pogues-xml2ddi/functions.fods
src/test/resources/pogues-xml-to-ddi/out.xml

157 b bis manage loop with multi references

---

src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/outputs/ddi/models.xsl

157-Ter manage loop with filter

---

src/main/resources/xslt/inputs/pogues-xml/functions.fods
src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/functions.fods

312A-BO Manage attribute NoDataByDefinition

---

pom.xml
src/main/resources/xslt/outputs/lunatic-xml/models.xsl
src/main/resources/xslt/post-processing/lunatic-xml/begin-question/begin-question.xml
src/main/resources/xslt/post-processing/lunatic-xml/end-question/end-question-business.xml
src/main/resources/xslt/post-processing/lunatic-xml/end-question/end-question-default.xml
src/main/resources/xslt/post-processing/lunatic-xml/end-question/end-question-household.xml
src/main/resources/xslt/post-processing/lunatic-xml/externalize-variables.xsl
src/main/resources/xslt/post-processing/lunatic-xml/insert-generic-questions.xsl
src/main/resources/xslt/post-processing/lunatic-xml/sort-components.xsl
src/main/resources/xslt/transformations/ddi2lunatic-xml/ddi2lunatic-xml-fixed.xsl
src/test/resources/ddi-to-lunatic-xml/out.xml
src/test/resources/params/in-to-out/default/form.xml

Revert "ddi2xml-lunatic : change lunatic-model"

---

pom.xml
src/main/resources/xslt/outputs/lunatic-xml/models.xsl
src/main/resources/xslt/post-processing/lunatic-xml/begin-question/begin-question.xml
src/main/resources/xslt/post-processing/lunatic-xml/end-question/end-question-business.xml
src/main/resources/xslt/post-processing/lunatic-xml/end-question/end-question-default.xml
src/main/resources/xslt/post-processing/lunatic-xml/end-question/end-question-household.xml
src/main/resources/xslt/post-processing/lunatic-xml/externalize-variables.xsl
src/main/resources/xslt/post-processing/lunatic-xml/insert-generic-questions.xsl
src/main/resources/xslt/post-processing/lunatic-xml/sort-components.xsl
src/main/resources/xslt/transformations/ddi2lunatic-xml/ddi2lunatic-xml-fixed.xsl
src/test/resources/ddi-to-lunatic-xml/out.xml
src/test/resources/params/in-to-out/default/form.xml

Changing the model on develop branch

ddi2xml-lunatic : change lunatic-model

---

src/main/resources/xslt/post-processing/fo/page-model/page-model-esa.fo

dev esa barcode

---

src/main/resources/xslt/post-processing/fo/page-model/page-model-esa.fo

Dev code barre

---

questionnaires/esem-2020-a00/parameters.xml
questionnaires/fpe-2019-x00/fo/v1/form/form.fo
questionnaires/simpsons/fo/simpsons/form/form.fo
src/main/resources/config/ddi2fo.xml
src/test/resources/ddi-to-fo/out.fo
src/test/resources/params/in-to-out/business/form.fo
src/test/resources/params/in-to-out/default/form.fo
src/test/resources/params/in-to-out/household/form.fo

Dev fo variable initialization

---

src/main/resources/xslt/inputs/ddi/functions.fods
src/main/resources/xslt/inputs/ddi/source-fixed.xsl
src/main/resources/xslt/inputs/ddi/templates.fods
src/main/resources/xslt/outputs/xforms/models.xsl
src/main/resources/xslt/post-processing/xforms/browsing.xsl
src/main/resources/xslt/post-processing/xforms/insee-model.xsl
src/main/resources/xslt/transformations/ddi2xforms/functions.fods
src/main/resources/xslt/util/debug.xsl
src/test/ant/script/build-configuration.xml
src/test/ant/script/build-in2out.xml

Revert "Dev occurrence filter"

---

src/main/resources/xslt/outputs/xforms/models.xsl
src/main/resources/xslt/post-processing/xforms/insert-welcome.xsl
src/test/resources/params/in-to-out/business/form.xhtml
src/test/resources/params/in-to-out/household/form.xhtml

- alt attribute on response img
- type of button for "cadreLegal" (warning : impact on css)

ddi2xforms : fix accessibilty issue

---

questionnaires/fpe-2019-x00/fo/v1/form/form.fo
questionnaires/simpsons/fo/simpsons/form/form.fo
questionnaires/simpsons/parameters.xml
src/main/resources/xslt/post-processing/fo/accompanying-mails.xsl
src/test/resources/ddi-to-fo/out.fo
src/test/resources/params/in-to-out/business/form.fo
src/test/resources/params/in-to-out/default/form.fo
src/test/resources/params/in-to-out/household/form.fo

- regression : Sting could no longer split pdf
+ out files update

bug with <![CDATA[#]]>

---

src/main/resources/xslt/outputs/xforms/models.xsl
src/main/resources/xslt/post-processing/xforms/insert-welcome.xsl
src/test/resources/params/in-to-out/business/form.xhtml
src/test/resources/params/in-to-out/household/form.xhtml

Revert "Dev accessibility"

---

src/main/resources/xslt/outputs/xforms/models.xsl
src/main/resources/xslt/post-processing/xforms/insert-welcome.xsl
src/test/resources/params/in-to-out/business/form.xhtml
src/test/resources/params/in-to-out/household/form.xhtml

Revert "Revert "Dev accessibility""

---

src/main/java/fr/insee/eno/transform/xsl/ClasspathURIResolver.java

This reverts commit 877ee7f76b2f081eb524305aaca0a56f8e061a46.

Revert "Fix error with relative import"

---

src/main/java/fr/insee/eno/Constants.java
src/main/java/fr/insee/eno/params/pipeline/PipeLineGeneratorImpl.java
src/main/java/fr/insee/eno/preprocessing/PoguesXmlInsertFilterLoopIntoQuestionTree.java
src/main/resources/params/schemas/Pipeline.xsd
src/main/resources/xslt/inputs/pogues-xml/functions.fods
src/main/resources/xslt/inputs/pogues-xml/source-fixed.xsl
src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/pre-processing/pogues-xml/goto-2-if-then-else.xsl
src/main/resources/xslt/pre-processing/pogues-xml/insert-filter-loop-into-question-tree.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/drivers.fods
src/main/resources/xslt/transformations/pogues-xml2ddi/functions.fods
src/main/resources/xslt/transformations/pogues-xml2ddi/pogues-xml2ddi-fixed.xsl
src/test/ant/script/in/build-in-pogues-xml.xml

By BulotF : 
based on the branch dev-ddi-filter
- manage loops as filters in the insert-filter-loop-into-question-tree.xsl file (when the beginning and the end are the same, the loop is inside the filter
- refactor loops to use the new driver Loop
- raise errors when a filter overlaps another filter or a loop overlaps a filter, a GoTo or another loop (2 GoTos : already managed ; a GoTo and a filter : management to do)
By ORogel : 
- add Java development for filter and the new preprocessing step

Dev ddi loop refactor

---

src/main/resources/xslt/post-processing/xforms/insert-welcome.xsl
src/test/resources/params/in-to-out/household/form.xhtml

Minor hotfix for the field before variable \$Enq_LibelleEnquete to display the right text on the web survey

Fixing field content before variable

---

pom.xml
src/main/resources/xslt/post-processing/fo/accompanying-mails/cnrCOL.fo
src/main/resources/xslt/post-processing/fo/accompanying-mails/medCOL.fo
src/test/resources/params/in-to-out/business/form.fo

Updating fo accompanying mails cnrCOL and medCOL 
(needed to also modify expected out for form.fo in test, in-to-out, business to fit new accompanying mails)

Dev fo update mail

---

pom.xml
src/main/resources/xslt/inputs/ddi/functions.fods
src/main/resources/xslt/inputs/ddi/templates.fods
src/main/resources/xslt/outputs/xforms/models.xsl
src/main/resources/xslt/transformations/ddi2xforms/functions.fods
src/test/resources/params/in-to-out/business/form.xhtml
src/test/resources/params/in-to-out/household/form.xhtml

Fixing issue for Insee data collection platform when specifying variable type in xforms bind for external variables when they were not initialized : now type is not specified for external variables. To do so :
- getter is-external-variable in ddi input has been created. It returns true when the variable is an external one, false otherwise
- modifying behaviour in xforms models.xsl to check if it is an external variable using aforementioned getter, and if it is, not putting type attribute in the xforms bind tag of that variable
Also needed :  Changing expected output for test in-to-out xforms, business and household, to fit with the new expected xforms

Hotfix xforms submiterror with extvar

---

pom.xml
src/main/resources/xslt/inputs/pogues-xml/functions.fods
src/main/resources/xslt/inputs/pogues-xml/source-fixed.xsl
src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/functions.fods

Adding support of formulas in loop minimum for ddi, from pogues-xml format
- Adding get-minimum-occurrences getter for pogues-xml2ddi
- Changing getters get-related-variables and get-ip-id in source-fixed.xsl to handle Minimum tag of Pogues
- Adding call to Command template for minimum in ddi models.xsl
Command ID for minimum is identified by the "MIN" keyword (ID for the maximum remains unchanged, to stay consistent)

Dev ddi min formula loop

---

doc/releases.md
pom.xml
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/pre-processing/pogues-xml/goto-2-if-then-else.xsl
src/main/resources/xslt/transformations/ddi2fo/drivers.fods

Preparing version 2.2.7 with following changelog :
- **[ddi2fo][core]** Fixing issue where the message related to a Filter would not be displayed in fo/pdf output
- **[poguesXML2ddi][core]** Fixing an issue with pogues2ddi transformation not preventing a GoTo that would point to a loop. It now crashes with an error
- **[poguesXML2ddi][core]** Retrieving name of loops from Pogues-XML into DDI

Dev multi v2.2.7

---

pom.xml
src/main/java/fr/insee/eno/service/MultiModelService.java
src/main/java/fr/insee/eno/service/NamingFileService.java
src/main/java/fr/insee/eno/utils/FileArchiver.java

Renaming fo files into zip for Insee integration.

Dev fo renaming file

---

src/main/resources/xslt/post-processing/lunatic-xml/sort-components.xsl

🆕 Getters: enolunatic:add-all-recursive-dependencies & enolunatic:get-all-dependencies
Only for conditionFilter dependencies : for each calculated variables, we retrieve its dependencies

Add all filterDependencies

---

doc/releases.md
pom.xml
src/main/java/fr/insee/eno/params/pipeline/PipelineGenerator.java
src/main/java/fr/insee/eno/params/validation/Validator.java
src/main/java/fr/insee/eno/postprocessing/lunaticxml/LunaticXMLVTLParserPostprocessor.java
src/main/java/fr/insee/eno/preprocessing/Preprocessor.java
src/main/java/fr/insee/eno/transform/xsl/XslTransformation.java

Corrections for javadoc errors

corrections java errors

---

pom.xml
src/main/resources/xslt/post-processing/fo/page-first/page-first-business.fo
src/test/resources/params/in-to-out/business/form.fo

Revert to non informative barcode in first page of business fo forms
This PR discards the modifications made by https://github.com/InseeFr/Eno/pull/359#issue-560900678 : Dev fo barcode info, released in Eno v2.2.1

Dev fo revertbarcode

---

src/test/ant/script/in/build-in-ddi.xml

Adding multimodal selection into ant script

Hotfix ant buildinddi multimodal

---

src/main/resources/xslt/inputs/pogues-xml/source-fixed.xsl

Pogues provides a more complete list of measurement units, update is necessary on the Eno side, i'm providing a small patch.

Updating measurement unit list

---

src/main/resources/xslt/post-processing/lunatic-xml/sort-components.xsl

Output lunatic : in post-processing sort-components, function is-var-used was not handling correctly case of first or last variable in dependencies if not used elsewhere, and limit case of single variable depedency

Output lunatic : fixing function checking if calculated variables are used

---

src/main/resources/xslt/post-processing/lunatic-xml/sort-components.xsl
src/test/resources/ddi-to-lunatic-xml/out.xml
src/test/resources/params/in-to-out/default/form.xml

fixing absence of the control field in the Table component

Hotfix lunatic tabcontrol

---

pom.xml
src/main/resources/xslt/post-processing/fo/page-first/page-first-business.fo
src/test/resources/params/in-to-out/business/form.fo

Changing the logo zone of business first page

Dev fo business logo

---

pom.xml
src/main/resources/xslt/inputs/pogues-xml/source-fixed.xsl

Updating unit measure list

---

eno-core/src/main/java/fr/insee/eno/core/converter/LunaticConverter.java
eno-core/src/main/java/fr/insee/eno/core/model/navigation/Loop.java
eno-core/src/main/java/fr/insee/eno/core/model/question/BooleanQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/DateQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/DynamicTableQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/MultipleChoiceQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/NumericQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/PairwiseQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/TableQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/TextQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/UniqueChoiceQuestion.java
eno-core/src/test/java/fr/insee/eno/core/mappers/MapperTestUtils.java
eno-core/src/test/java/fr/insee/eno/core/mappers/ddi/CodeResponseTest.java
eno-core/src/test/java/fr/insee/eno/core/mappers/ddi/EnoQuestionnaireTest.java
eno-core/src/test/java/fr/insee/eno/core/mappers/lunatic/BooleanQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mappers/lunatic/DateQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mappers/lunatic/LoopTest.java
eno-core/src/test/java/fr/insee/eno/core/mappers/lunatic/MultipleChoiceQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mappers/lunatic/NumericQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mappers/lunatic/PairwiseQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mappers/lunatic/TableQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mappers/lunatic/TextQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mappers/lunatic/UniqueChoiceQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/sandbox/LunaticTests.java

Mostly Lunatic components have a `"componentType"` property, which is required for Lunatic.
This information is not automatically inserted by Lunatic-Model json serializer => mapped it in every concerned components in Eno.

V3 lunatic component types

---

eno-core/src/main/java/fr/insee/eno/core/DDIToLunatic.java
eno-core/src/main/java/fr/insee/eno/core/output/LunaticSerializer.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/SimpleGenerationController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/utils/V3ControllerUtils.java
eno-ws/src/main/java/fr/insee/eno/ws/service/DDIToLunaticService.java

Restore redirection to Eno legacy web-service for Lunatic XML endpoint.

feat: lunatic xml endpoint back to legacy

---

.github/workflows/v3-build-docker.yml
settings.gradle

Thanks to @davdarras CI in [Pogues-Model](https://github.com/InseeFr/Pogues-Model), we have Pogues-Model in maven central.

ci: pogues-model from maven central

---

eno-core/build.gradle
eno-core/src/main/java/fr/insee/eno/core/DDIToLunatic.java
eno-core/src/main/java/fr/insee/eno/core/converter/JsonLunaticConverter.java
eno-core/src/main/java/fr/insee/eno/core/converter/JsonMissingBlockConverter.java
eno-core/src/main/java/fr/insee/eno/core/exceptions/business/LunaticProcessingException.java
eno-core/src/main/java/fr/insee/eno/core/model/lunatic/MissingBlock.java
eno-core/src/main/java/fr/insee/eno/core/processing/LunaticProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/impl/LunaticAddMissingVariables.java
eno-core/src/test/java/fr/insee/eno/core/converter/JsonMissingBlockConverterTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/impl/LunaticAddMissingVariablesTest.java

- add missing response on components
- add missing variables
- add missingblock object

feat: add missing variables to questionnaire json object

---

src/main/resources/xslt/post-processing/lunatic-xml/pagination.xsl
src/test/resources/ddi-to-lunatic-xml/out.xml

https://github.com/InseeFr/Eno/issues/650

Dev fix roster for loop pagination

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/EnoToLunatic.java
eno-core/src/main/java/fr/insee/eno/core/parameter/EnoParameters.java
eno-core/src/main/java/fr/insee/eno/core/parameter/LunaticParameters.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/LunaticProcessing.java
eno-core/src/test/java/fr/insee/eno/core/parameter/EnoParameterTest.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/GenerationController.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/V3ParameterController.java

#714 
- Parameter file name in function of context/mode/format
- Adjust parameters with new specifications

feat: adjust lunatic parameters

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/common/steps/EnoAddCommentSection.java
eno-core/src/main/java/fr/insee/eno/core/processing/common/steps/EnoAddResponseTimeSection.java

#723 
https://github.com/InseeFr/Eno/issues/723#issuecomment-1737390977

fix: correct vtl labels in begin and end questions

---

build.gradle
eno-core/build.gradle

build: update depencencies

---

pom.xml

Fix `UnsupportedOperationException` in some XSLT cases.
NB: related to https://saxonica.plan.io/issues/5633

hotfix: saxon bug

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/common/steps/EnoAddIdentificationSection.java
eno-core/src/test/java/fr/insee/eno/core/processing/common/steps/EnoAddIdentificationSectionTest.java

In business questionnaires, an "identification" question is added at the beginning of the questionnaire.
(Before this, the associated processing was throwing and "unimplemented" exception.)

feat: identification section

---

.github/workflows/build-release.yml
.github/workflows/test.yml
README.md
pom.xml

build: java 17

---

pom.xml
src/main/resources/xslt/outputs/xforms/models.xsl
src/main/resources/xslt/post-processing/xforms/browsing.xsl
src/test/resources/ddi-to-xforms/out.xhtml
src/test/resources/params/in-to-out/business/form.xhtml
src/test/resources/params/in-to-out/default/form.xhtml
src/test/resources/params/in-to-out/household/form.xhtml

- xf:input replaced by fr:date
- in triggers, xxf:action before xxf:hide instead of after
- for fr:section inside xf:repeat : xf:bind/@relevant is enriched by CurrentSectionName = the section name (stopped working)

ddi2xforms : Orbeon 2022

---

pom.xml
src/main/resources/xslt/outputs/lunatic-xml/models.xsl

- #795 
- fix(pairwise): remove pariwse x/yAxis condition filters in Eno

fix(pairwise): remove pairwise filter x <> y

---

build.gradle
ddi-beans/build.gradle
eno-core/build.gradle
eno-treatments/build.gradle
eno-ws/build.gradle
gradle.properties
gradle/wrapper/gradle-wrapper.properties
settings.gradle

build: upgrade gradle wrapper

---

.github/workflows/create-release.yml
.github/workflows/create-snapshot.yml
.github/workflows/sonar.yml
Dockerfile
build.gradle

build: java 21

---

eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddMissingVariables.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddMissingVariablesPairwiseTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddMissingVariablesTest.java

fix: missing variable values

---

eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddMissingVariables.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddMissingVariablesTest.java

fix: missing variables in non paginated loops

---

.github/workflows/create-release.yml
.github/workflows/create-snapshot.yml
.github/workflows/sonar.yml
build.gradle
eno-core/src/main/java/fr/insee/eno/core/model/question/Question.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddMissingVariables.java
eno-core/src/main/java/fr/insee/eno/core/utils/LunaticUtils.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddMissingVariablesPairwiseTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddMissingVariablesTest.java
eno-treatments/build.gradle
eno-ws/src/main/java/fr/insee/eno/ws/config/OpenApiConfiguration.java
eno-ws/src/main/resources/application.properties

- make the `eno.ws.url` used for swagger property optional (this property caused issues in some envrironements)
- fixes on Lunatic missing variables
- update dependencies

V3 next: fix missing variables

---

.github/workflows/create-release.yml
.github/workflows/sonar.yml
CHANGELOG.md
build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticVariablesValues.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticVariablesValuesTest.java
settings.gradle

fix: lunatic scalar variable values

---

.github/workflows/create-release.yml
.github/workflows/create-snapshot.yml
eno-treatments/build.gradle
eno-ws/build.gradle

build: update dependencies

---

eno-core/src/main/java/fr/insee/eno/core/model/variable/VariableGroup.java
eno-core/src/main/java/fr/insee/eno/core/serialize/DDIDeserializer.java
eno-core/src/main/java/fr/insee/eno/core/serialize/LunaticSerializer.java
eno-core/src/main/java/fr/insee/eno/core/serialize/PoguesDeserializer.java
eno-core/src/main/java/fr/insee/eno/core/utils/DDIUtils.java
eno-core/src/main/java/fr/insee/eno/core/utils/EnoSpelEngine.java
eno-core/src/main/java/fr/insee/eno/core/utils/LunaticUtils.java
eno-core/src/main/java/fr/insee/eno/core/utils/RomanNumber.java
eno-core/src/main/java/fr/insee/eno/core/utils/VtlSyntaxUtils.java
eno-core/src/main/java/fr/insee/eno/core/utils/XpathToVtl.java
eno-ws/src/main/java/fr/insee/eno/ws/controller/UtilsController.java

Add some javadoc and add/clean up logging in serializer classes.

refactor: more javadoc and little logging enhancement

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/parameter/EnoParameters.java

feat: business first page parameter

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticPairwiseResizingLogic.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticAddResizingTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticPairwiseResizingLogicTest.java
settings.gradle

cf.
- InseeFr/Lunatic#883
- InseeFr/Lunatic#885
- InseeFr/Lunatic-Model#210

fix: resizing pairwise variables size

---

pom.xml
src/main/resources/xslt/outputs/ddi/models.xsl
src/test/resources/pogues-xml-to-ddi/out.xml

remove xhtml bold for clarification label

---

pom.xml
src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/outputs/ddi/models.xsl

- Add VariableGroup with:
-  TypeOfVariableGroup = PairwiseLink 
- BasedOnReference: the QuestionItem "PAIRWISE"
- Add a VariableGroupReference in the "loop" VariableGroup
- move the VariableReference of the pairwise variables from "Instrument" VariableGroup to "PairwiseLink" VariableGroup

Manage pairwise VariableGroup

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/model/navigation/Control.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddControlFormat.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/ddi/ControlTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/ControlTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddControlFormatTest.java
eno-core/src/test/resources/integration/ddi/ddi-controls.xml
eno-core/src/test/resources/integration/pogues/pogues-controls.json

Reverts temporary change made in version 3.15.6
\+ add some unit tests
- #942

feat: restore controls criticality

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticFinalizePairwise.java
eno-core/src/test/java/fr/insee/eno/core/DDIToLunaticTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticFinalizePairwiseTest.java

fix: null pointer exception in "dsfr" processing for pairwise

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/EnoToLunatic.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/LunaticProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticInputNumberDescription.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticInputNumberDescriptionTest.java

feat: generate description for lunatic input numbers

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/out/LunaticProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticSequenceDescription.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticSequenceDescriptionTest.java
eno-core/src/test/resources/integration/ddi/ddi-declarations.xml

feat: move declaration to description for dsfr sequences

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/common/EnoProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/common/steps/EnoAddPrefixInQuestionLabels.java
eno-core/src/test/java/fr/insee/eno/core/processing/common/steps/EnoAddCommentSectionTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/common/steps/EnoAddPrefixInQuestionLabelsTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/common/steps/EnoAddResponseTimeSectionTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticResponseTimeQuestionPaginationTest.java

fix: lunatic question numbering

---

build.gradle
eno-treatments/src/main/java/fr/insee/eno/treatments/LunaticSuggesterSpecificTreatment.java
eno-treatments/src/test/java/fr/insee/eno/treatments/LunaticSuggesterSpecificTreatmentTest.java

fix: suggester specific treatment dsfr

---

pom.xml
src/main/resources/xslt/inputs/pogues-xml/templates.fods

Label instead of AlternativeLabel

fix celllabel address for nodatabydefinition

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticFinalizePairwise.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticQuestionComponentTest.java

fix: lunatic pairwise label

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticInputNumberDescription.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticInputNumberDescriptionTest.java

fix: lunatic input number description with large numbers

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/model/question/table/UniqueChoiceCell.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/table/ComplexMultipleChoiceQuestionProcessingTest.java
settings.gradle

feat: horizontal unique choice cells in lunatic tables

---

pom.xml
src/main/resources/xslt/inputs/pogues-xml/functions.fods
src/main/resources/xslt/inputs/pogues-xml/source-fixed.xsl
src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/functions.fods
src/test/resources/pogues-xml-to-ddi/out.xml

- fix on the roundabout feature
- dependencies update

V2 next: 2.9.10

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/exceptions/business/LunaticVariableConflictException.java
eno-core/src/main/java/fr/insee/eno/core/model/EnoQuestionnaire.java
eno-core/src/main/java/fr/insee/eno/core/model/navigation/Control.java
eno-core/src/main/java/fr/insee/eno/core/model/navigation/Loop.java
eno-core/src/main/java/fr/insee/eno/core/model/sequence/RoundaboutSequence.java
eno-core/src/main/java/fr/insee/eno/core/processing/common/steps/EnoModeSelection.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/LunaticProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoops.java
eno-core/src/main/java/fr/insee/eno/core/reference/EnoCatalog.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/ddi/RoundaboutSequenceTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoopsTest.java
eno-core/src/test/resources/integration/ddi/ddi-roundabout.xml
eno-core/src/test/resources/integration/pogues/pogues-loop-except.json
eno-core/src/test/resources/integration/pogues/pogues-roundabout.json
settings.gradle

feat: roundabout

---

.github/workflows/create-snapshot.yml
build.gradle
eno-core/src/main/java/fr/insee/eno/core/model/navigation/ComponentFilter.java
eno-core/src/main/java/fr/insee/eno/core/model/navigation/Filter.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/DDIInProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIMarkRoundaboutFilters.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/ddi/DDIMarkRoundaboutFiltersTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoopsTest.java

The filter defined for the roundabout is described as an "occurrence filter" in DDI, a larger refactor would be necessary to handle this properly, this commit fixes the roundabout case.

fix: roundabout filter

---

.github/workflows/create-release.yml
.github/workflows/create-snapshot.yml
pom.xml

- build: dependencies update
- ci: maven central publish

V2 next: 2.9.11

---

.github/workflows/create-release.yml
.github/workflows/create-snapshot.yml
.github/workflows/sonar.yml
build.gradle
eno-treatments/build.gradle

- build: dependencies update
- ci: replace deprecated gradle build action

V3 next: 3.23.6

---

build.gradle
eno-core/src/main/java/fr/insee/eno/core/processing/out/LunaticProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticEditLabelTypes.java

fix: set sequence label type to VTL

---

eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticInputNumberDescription.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticInputNumberDescriptionTest.java

fix: set type of generated descriptions to TXT

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/exceptions/business/InvalidSuggesterExpression.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/LunaticProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticSuggesterOptionResponses.java
eno-core/src/main/java/fr/insee/eno/core/utils/VtlSyntaxUtils.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticSuggesterOptionResponsesTest.java
eno-core/src/test/resources/integration/ddi/ddi-suggester-options.xml
eno-core/src/test/resources/integration/pogues/pogues-suggester-options.json
settings.gradle.kts

feat(lunatic): option responses in suggesters

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/exceptions/business/InvalidSuggesterExpression.java
eno-core/src/main/java/fr/insee/eno/core/mappers/InMapper.java
eno-core/src/main/java/fr/insee/eno/core/mappers/PoguesMapper.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/LunaticProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticSuggesterOptionResponses.java
eno-core/src/main/java/fr/insee/eno/core/utils/VtlSyntaxUtils.java
eno-core/src/test/java/fr/insee/eno/core/converter/DDIConverterTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticSuggesterOptionResponsesTest.java
eno-core/src/test/resources/integration/ddi/ddi-suggester-options.xml
eno-core/src/test/resources/integration/pogues/pogues-suggester-options.json
settings.gradle.kts

Suggester with multi-variable response
\+ some refactor

V3 next: 3.27.0

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIInsertDetailResponses.java
eno-treatments/build.gradle.kts
eno-ws/src/main/java/fr/insee/eno/ws/controller/HomeController.java
gradle/wrapper/gradle-wrapper.properties

- dependencies update: includes an upgrade of spring boot which fixes a security issue
- fix Sonar complaint about the redirection controller
- some refactor

V3 next: 3.27.1

---

src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/outputs/ddi/models.xsl

Add checks for roundabout

---

pom.xml
src/main/resources/xslt/inputs/pogues-xml/source-fixed.xsl
src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/post-processing/xforms/insert-welcome.xsl
src/test/resources/params/in-to-out/business/form.xhtml
src/test/resources/params/in-to-out/household/form.xhtml

V2 next: 2.10.0

---

eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticSuggesterOptionResponses.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticSuggesterOptionResponsesTest.java
eno-core/src/test/resources/integration/ddi/ddi-suggester-options-table.xml
eno-core/src/test/resources/integration/pogues/pogues-roundabout-subsequence.json
eno-core/src/test/resources/integration/pogues/pogues-suggester-options-table.json
settings.gradle.kts

- https://github.com/InseeFr/Eno/issues/1046#issuecomment-2416027625

fix: allow suggester with option responses in tables

---

pom.xml
src/main/resources/xslt/post-processing/xforms/browsing.xsl

A parenthesis was missing... 
Needed by Ecmoss

fix filter for loop of pages (xforms)

---

pom.xml
src/main/resources/xslt/inputs/pogues-xml/functions.fods
src/main/resources/xslt/inputs/pogues-xml/source-fixed.xsl
src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/post-processing/xforms/browsing.xsl
src/main/resources/xslt/transformations/pogues-xml2ddi/drivers.fods
src/main/resources/xslt/transformations/pogues-xml2ddi/functions.fods

- update dependencies
- fix on the xforms format
- feature: dynamic tables with size defined with an expression (in Pogues -> DDI)

V2 next: 2.11.0

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/model/question/DynamicTableQuestion.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/table/DynamicTableQuestionProcessing.java

refactor: dynamic table mapping

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/model/question/DynamicTableQuestion.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/table/DynamicTableQuestionProcessing.java
eno-core/src/main/java/fr/insee/eno/core/utils/LunaticUtils.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticLoopResizingLogicTest.java
gradle/wrapper/gradle-wrapper.properties

On aurait pu faire cette release plus tôt, my bad

Release 3.29.1

---

eno-core/src/main/java/fr/insee/eno/core/model/question/NumericQuestion.java
eno-core/src/main/java/fr/insee/eno/core/processing/common/steps/EnoAddResponseTimeSection.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/ddi/DDIMoveUnitInQuestions.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticEditLabelTypes.java

cf. retour de review https://github.com/InseeFr/Eno/pull/1175#discussion_r1883941522
@corbininsee

refactor(dynamic unit): code simplifications

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/processing/common/steps/EnoAddResponseTimeSection.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddControlFormat.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoops.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticAddResizing.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticLoopResizingLogic.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticRosterResizingLogic.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddControlFormatTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoopsTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticRosterResizingLogicTest.java
eno-core/src/test/resources/integration/ddi/ddi-roundabout.xml
eno-core/src/test/resources/integration/pogues/pogues-roundabout.json

Corrections de bugs, voir les commits pour ceux qui ne sont pas liés à une PR (bugs mineurs)

V3 next: 3.31.4

---

eno-core/src/main/java/fr/insee/eno/core/mappers/InMapper.java
eno-core/src/main/java/fr/insee/eno/core/model/EnoQuestionnaire.java
eno-core/src/main/java/fr/insee/eno/core/model/code/CodeItem.java
eno-core/src/main/java/fr/insee/eno/core/model/code/CodeList.java
eno-core/src/main/java/fr/insee/eno/core/model/label/Label.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/PoguesInProcessing.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/steps/pogues/PoguesNestedCodeLists.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/CodeListTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/pogues/PoguesNestedCodeListsTest.java

Mapping des listes de code de Pogues vers Eno
Au passage : un peu de refacto cf. suggestions intelliJ en allant voir le code de `InMapper`

feat(pogues mapping): code lists

---

eno-core/src/main/java/fr/insee/eno/core/EnoToLunatic.java
eno-core/src/main/java/fr/insee/eno/core/model/EnoQuestionnaire.java
eno-core/src/main/java/fr/insee/eno/core/model/sequence/AbstractSequence.java
eno-core/src/main/java/fr/insee/eno/core/model/sequence/Sequence.java
eno-core/src/main/java/fr/insee/eno/core/model/sequence/Subsequence.java
eno-core/src/test/java/fr/insee/eno/core/DDIToLunaticTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/SequenceTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/SubsequenceTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/VariableTest.java
eno-core/src/test/resources/integration/ddi/ddi-subsequences.xml
eno-core/src/test/resources/integration/pogues/pogues-subsequences.json

Mapping des séquences et des sous-séquences de Pogues.

feat(pogues mapping): sequences 

---

eno-core/src/main/java/fr/insee/eno/core/converter/PoguesConverter.java
eno-core/src/main/java/fr/insee/eno/core/converter/PoguesSingleResponseQuestionConversion.java
eno-core/src/main/java/fr/insee/eno/core/mappers/PoguesMapper.java
eno-core/src/main/java/fr/insee/eno/core/model/EnoQuestionnaire.java
eno-core/src/main/java/fr/insee/eno/core/model/label/DynamicLabel.java
eno-core/src/main/java/fr/insee/eno/core/model/question/Question.java
eno-core/src/main/java/fr/insee/eno/core/model/question/SingleResponseQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/TextQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/response/Response.java
eno-core/src/main/java/fr/insee/eno/core/model/sequence/AbstractSequence.java
eno-core/src/main/java/fr/insee/eno/core/utils/PoguesUtils.java
eno-core/src/test/java/fr/insee/eno/core/PoguesToLunaticTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/TextQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/TextQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/TextQuestionTest.java

Mapping des questions de type texte de Pogues.

feat(pogues mapping): text questions

---

eno-core/src/main/java/fr/insee/eno/core/model/sequence/AbstractSequence.java
eno-core/src/main/java/fr/insee/eno/core/model/sequence/StructureItemReference.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/StructureItemReferenceTest.java

Keep references of sequence and subsequences content. Required to sort Lunatic components.

feat(pogues mapping): sequences structure

---

eno-core/src/main/java/fr/insee/eno/core/converter/PoguesConverter.java
eno-core/src/main/java/fr/insee/eno/core/converter/PoguesMultipleChoiceQuestionConverter.java
eno-core/src/main/java/fr/insee/eno/core/converter/PoguesSingleResponseQuestionConversion.java
eno-core/src/main/java/fr/insee/eno/core/model/EnoQuestionnaire.java
eno-core/src/main/java/fr/insee/eno/core/model/question/MultipleResponseQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/UniqueChoiceQuestion.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/ComplexMultipleChoiceQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/DynamicTableQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/SimpleMultipleChoiceQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/TableQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/UniqueChoiceQuestionTest.java

Implémentation de la logique de conversion : 
- des questions à choix unique 
- des questions à réponses multiples (questions à choix multiples, tableaux, tableaux dynamique)
Le mapping de ces types de question est pas encore complet.

feat(pogues mapping): multiple response questions conversion

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticRosterResizingLogic.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/resizing/LunaticRosterResizingLogicTest.java
eno-core/src/test/resources/functional/ddi/ddi-m5o3qhu0.xml

En présence de colonnes non-collectées dans un tableau dynamique, `NullPointerException` au moment de l'étape de génération du _resizing_ Lunatic.

fix: null pointer exception with non collected cells in dynamic table

---

eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/pagination/LunaticPaginationQuestionMode.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/pagination/LunaticPaginationSequenceMode.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/pagination/LunaticPaginationTest.java

fix: loop attributes change according to pagination

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/converter/LunaticConverter.java
eno-core/src/main/java/fr/insee/eno/core/model/question/SuggesterQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/response/ArbitraryResponse.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/pogues/SuggesterQuestionTest.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/SuggesterQuestionTest.java

Et voilà enfin la génération pour la fonctionnalité de réponse "champ libre" pour les questions à choix unique en auto-complétion.

feat: suggester arbitrary response

---

build.gradle.kts
settings.gradle.kts

Remove unused "EDITED" "FORCED" etc values of Lunatic collected variables in serialized questionnaires.
cf.
- InseeFr/Lunatic-Model#280

feat(lunatic): remove unused edited forced etc values

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/reference/EnoCatalog.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/ddi/DDIResolveVariableReferencesInLabelsTest.java
eno-core/src/test/resources/integration/ddi/ddi-table-custom-header.xml
eno-core/src/test/resources/integration/pogues/pogues-table-custom-header.json

cf.
- #1218 
mais en hotfix depuis la main

fix: custom label in table headers

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/mappers/InMapper.java
eno-core/src/main/java/fr/insee/eno/core/processing/in/PoguesInProcessing.java
eno-core/src/main/java/fr/insee/eno/core/reference/EnoCatalog.java
eno-core/src/test/java/fr/insee/eno/core/processing/in/steps/ddi/DDIResolveVariableReferencesInLabelsTest.java
eno-core/src/test/resources/integration/ddi/ddi-table-custom-header.xml
eno-core/src/test/resources/integration/pogues/pogues-table-custom-header.json

- bug sur les libellés dans les headers de tableaux
- bug sur la génération en présence de modalités "autre précisez" dans les QCM

hotfix: 3.33.2

---

eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddControlFormat.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/control/DurationControlExpression.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/control/DurationControlMessage.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/control/LunaticDatepickerControl.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/control/LunaticDurationControl.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/control/LunaticFormatControl.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/control/LunaticInputNumberControl.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/control/LunaticRosterControl.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/control/LunaticTableControls.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/pagination/LunaticAddPageNumbers.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddControlFormatTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/control/DurationControlExpressionTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/control/DurationControlMessageTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/control/LunaticDurationControlTest.java

J'ai refacto en lego / corrigé qq petits trucs.
Une PR pour voir les diff (mais au final j'ai beaucoup bougé les trucs donc le diff est sans doute pas simple à lire...)

refactor: lunatic duration format controls

---

eno-core/build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/utils/vtl/VtlSyntaxUtils.java
eno-core/src/main/java/fr/insee/eno/core/utils/vtl/VtlTokensListener.java
eno-core/src/test/java/fr/insee/eno/core/utils/vtl/VtlSyntaxUtilsTest.java

refactor(optimize cleaning): vtl functions

---

eno-core/src/main/java/fr/insee/eno/core/mappers/InMapper.java

@JulienCarmona finalement j'ai trouvé un moyen de refacto pour rendre le code plus clair au sujet des checks sur la taille des listes dans le mapper "in".
cf. 
- #1220 
- https://github.com/InseeFr/Eno/pull/1220#discussion_r1963790155

refactor: list size checks in input mapper

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/converter/PoguesTableCellConversion.java
eno-core/src/main/java/fr/insee/eno/core/model/navigation/ComponentFilter.java
eno-core/src/main/java/fr/insee/eno/core/model/question/ComplexMultipleChoiceQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/DateQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/DurationQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/DynamicTableQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/NumericQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/SingleResponseQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/SuggesterQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/TableQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/TextQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/UniqueChoiceQuestion.java
eno-core/src/main/java/fr/insee/eno/core/model/question/table/ResponseCell.java
eno-core/src/main/java/fr/insee/eno/core/utils/PoguesUtils.java
eno-core/src/test/java/fr/insee/eno/core/mapping/out/lunatic/TableCellsFilterTest.java
eno-core/src/test/resources/functional/ddi/cells-filtered/ddi-m92r209h.xml
eno-core/src/test/resources/functional/lunatic/cells-filtered/lunatic-m92r209h.json
eno-core/src/test/resources/functional/pogues/cells-filtered/pogues-m92r209h.json
eno-core/src/test/resources/integration/ddi/ddi-table-cell-filter.xml
eno-core/src/test/resources/integration/pogues/pogues-table-cell-filter.json
settings.gradle.kts

- Suite à la montée de version de Lunatic-Model (4.2.0), l'attribut mandatory n'est présent que dans certains composant (cf: https://github.com/InseeFr/Lunatic-Model/pull/285 & https://github.com/InseeFr/Lunatic-Model/pull/288)
- création de données de test (pogues + ddi + lunatic )
- un premier mapping pogues->Lunatic est fait
- reste à tester le mapping proposé.

feat: table dynamic cell filters

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/cleaning/CleaningUtils.java

Correction du NullPointerException.

fix: NPE cleaning utils

---

pom.xml
questionnaires/esem-2020-a00/fo/m1/form/courrier_type_esem2020a00m1cnrCOL.fo
questionnaires/esem-2020-a00/fo/m1/form/courrier_type_esem2020a00m1medCOL.fo
questionnaires/esem-2020-a00/fo/m1/form/courrier_type_esem2020a00m1relanceCOL.fo
questionnaires/esem-2020-a00/fo/m1/form/form.fo
src/main/resources/xslt/post-processing/fo/accompanying-mails/accompagnementCOL.fo
src/main/resources/xslt/post-processing/fo/accompanying-mails/cnrCOL.fo
src/main/resources/xslt/post-processing/fo/accompanying-mails/entreeCOL.fo
src/main/resources/xslt/post-processing/fo/accompanying-mails/medCOL.fo
src/main/resources/xslt/post-processing/fo/accompanying-mails/ouvertureCOL.fo
src/main/resources/xslt/post-processing/fo/accompanying-mails/relanceCOL.fo
src/main/resources/xslt/post-processing/fo/page-first/page-first-business.fo
src/main/resources/xslt/post-processing/fo/page-model/page-model-business.fo
src/test/resources/params/in-to-out/business/form.fo

Dans les questionnaires papier générés par Eno figure en dur une référence à un fichier "logo de l'Insee".
Dans le contexte de changement de logo de l'institut (\+ changement de nom de variable dans d'autres outils), il faut modifier cette référence.

feat(paper): new insee logo reference

---

.github/workflows/create-release.yml
.github/workflows/create-snapshot.yml

syntax error sur un if + fetch depth 0 pour lire le tag précédent

ci: repair release workflow

---

eno-core/src/main/java/fr/insee/eno/core/exceptions/business/VariableGroupException.java
eno-core/src/main/java/fr/insee/eno/core/model/variable/VariableGroup.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticFinalizePairwise.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticVariablesDimension.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/cleaning/LunaticAddCleaning.java
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/cleaning/LunaticPairwiseQuestionCleaning.java
eno-core/src/main/java/fr/insee/eno/core/utils/LunaticUtils.java
eno-core/src/main/java/fr/insee/eno/core/utils/vtl/VtlSyntaxUtils.java
eno-core/src/test/java/fr/insee/eno/core/mapping/in/ddi/VariableGroupTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticAddCleaningTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticFinalizePairwiseTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticVariableDimensionTest.java
eno-core/src/test/java/fr/insee/eno/core/utils/vtl/VtlSyntaxUtilsTest.java
eno-core/src/test/resources/integration/ddi/ddi-pairwise.xml

- add special cleaning for pairwise
- add conditionFilter for empty pairwise source variable
See: https://github.com/InseeFr/Lunatic/pull/1251
We need to update "iterationReference" for pairwiseQuestion

feat: pairwise improvments

---

pom.xml
src/main/resources/xslt/inputs/ddi/functions.fods
src/main/resources/xslt/inputs/ddi/source-fixed.xsl
src/main/resources/xslt/inputs/ddi/templates.fods
src/main/resources/xslt/inputs/pogues-xml/functions.fods
src/main/resources/xslt/inputs/pogues-xml/source-fixed.xsl
src/main/resources/xslt/inputs/pogues-xml/templates.fods
src/main/resources/xslt/outputs/ddi/models.xsl
src/main/resources/xslt/outputs/fo/models.xsl
src/main/resources/xslt/transformations/ddi2fo/functions.fods
src/main/resources/xslt/transformations/pogues-xml2ddi/functions.fods
src/test/resources/ddi-to-fo/out.fo
src/test/resources/params/in-to-out/business/form.fo
src/test/resources/pogues-xml-to-ddi/suggester-arbitrary/in-loop.xml

- renommage de get-fixed-lines en get-condition-for-continuation
- conservation des anciennes structures + ajout des nouvelles :
- si type = number, on renseigne min et/ou max (y compris dans le cas size)
- si type = VTL, on renseigne ConditionForContinuation (N.B. Le min au format VTL est perdu en DDI)
- les value associées à un type VTL sont considérées comme des formules

feat(pogues2ddi): new format for min max in dynamic table

---

src/main/resources/xslt/inputs/pogues-xml/templates.fods

manage minimum, maximum and size instead of Minimum and Maximum for loops

feat(loops): minimum, maximum and size instead of Minimum and Maximum

---

pom.xml
src/main/resources/xslt/inputs/pogues-xml/templates.fods

Problème lié au commit sur le changement : 
`Minimum` , `Maximum` -> `minimum`, `maximum` / `size` 
Cause exacte pas précisément identifiée, en attendant : PR pour simplement revert ce changement.

fix(pogues2ddi): min max loop props

---

build.gradle.kts
eno-core/src/main/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticLoopResolution.java
eno-core/src/main/java/fr/insee/eno/core/utils/vtl/VtlSyntaxUtils.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticLoopFilterIntegrationTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticLoopResolutionTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/LunaticRoundaboutLoopsTest.java
eno-core/src/test/java/fr/insee/eno/core/processing/out/steps/lunatic/shapefrom/LunaticHierarchyShapeFromTest.java
eno-core/src/test/java/fr/insee/eno/core/utils/vtl/VtlSyntaxUtilsTest.java
eno-core/src/test/resources/integration/ddi/ddi-loop-filter.xml
eno-core/src/test/resources/integration/pogues/pogues-loop-filter.json

Fix regression caused by https://github.com/InseeFr/Eno/pull/1327

fix: loop condition
